using OpenQA.Selenium.Chrome;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Reflection.Emit;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Bot
{
    public partial class insta : Form
    {
        public insta()
        {
            InitializeComponent();
        }
        private List<string[]> instas = new List<string[]>
        {
          new string[] {"beydazog", "UPmedya19!!!!" },
new string[] {"aysegulbarutcuoglu", "UPmedya19!!!!" },
new string[] {"sefakadirbasar", "UPmedya19!!!!" },
new string[] {"elifetgabasegmez", "UPmedya19!!!!" },
new string[] {"nevinbastepe", "UPmedya19!!!!" },
new string[] {"mahperibastopcu", "UPmedya19!!!!" },
new string[] {"erolozgurbastug", "UPmedya19!!!!" },
new string[] {"atakbatar", "UPmedya19!!!!" },
new string[] {"safabatga", "UPmedya19!!!!" },
new string[] {"gokmenbattal", "UPmedya19!!!!" },
new string[] {"fazilerembatuk", "UPmedya19!!!!" },
new string[] {"bensubatur", "UPmedya19!!!!" },
new string[] {"nazimorhunbaturalp", "UPmedya19!!!!" },
new string[] {"safaahmetbaydar", "UPmedya19!!!!" },
new string[] {"demircanbaydil", "UPmedya19!!!!" },
new string[] {"burcinkubrabaykal", "UPmedya19!!!!" },
new string[] {"dervishalukbaykan", "UPmedya19!!!!" },
new string[] {"taylanremzibaykus", "UPmedya19!!!!" },
new string[] {"abdulvahapbayrakoglu", "UPmedya19!!!!" },
new string[] {"aygunbayram", "UPmedya19!!!!" },
new string[] {"aylabaytin", "UPmedya19!!!!" },
new string[] {"kubilaybarisbegic", "UPmedya19!!!!" },
new string[] {"mustafasamedbegenilmis", "UPmedya19!!!!" },
new string[] {"berfindilaybekaroglu", "UPmedya19!!!!" },
new string[] {"ibrahimonatbengi", "UPmedya19!!!!" },
new string[] {"jutenyabenan", "UPmedya19!!!!" },
new string[] {"hulkibent", "UPmedya19!!!!" },
new string[] {"mustafadogukanberberoglu", "UPmedya19!!!!" },
new string[] {"hunerberk", "UPmedya19!!!!" },
new string[] {"busegizemberker", "UPmedya19!!!!" },
new string[] {"halimebeydag", "UPmedya19!!!!" },
new string[] {"didembicaksiz", "UPmedya19!!!!" },
new string[] {"mihrinazbilal", "UPmedya19!!!!" },
new string[] {"lalbilgec", "UPmedya19!!!!" },
new string[] {"senaybilgen", "UPmedya19!!!!" },
new string[] {"remzibilgi", "UPmedya19!!!!" },
new string[] {"armaganbilgic", "UPmedya19!!!!" },
new string[] {"celikbilgir", "UPmedya19!!!!" },
new string[] {"kubratansubilgit", "UPmedya19!!!!" },
new string[] {"ulucemrebinbay", "UPmedya19!!!!" },
new string[] {"mehmetbugrahanbirgili", "UPmedya19!!!!" },
new string[] {"doguscanbiriz", "UPmedya19!!!!" },
new string[] {"altanboy", "UPmedya19!!!!" },
new string[] {"bengisuboya", "UPmedya19!!!!" },
new string[] {"onurtaylanboylu", "UPmedya19!!!!" },
new string[] {"ayserenboyuktas", "UPmedya19!!!!" },
new string[] {"pekinboz", "UPmedya19!!!!" },
new string[] {"aksubozdag", "UPmedya19!!!!" },
new string[] {"arkanbozdemir", "UPmedya19!!!!" },
new string[] {"iltemboztepe", "UPmedya19!!!!" },
new string[] {"betulbozyer", "UPmedya19!!!!" },
new string[] {"ogunbolge", "UPmedya19!!!!" },
new string[] {"ibrahimhakkibugey", "UPmedya19!!!!" },
new string[] {"onaybugdaypinari", "UPmedya19!!!!" },
new string[] {"cankizbulgan", "UPmedya19!!!!" },
new string[] {"arzucanbulgur", "UPmedya19!!!!" },
new string[] {"asiyeburabak", "UPmedya19!!!!" },
new string[] {"ahmetyasinburak", "UPmedya19!!!!" },
new string[] {"yaprakbural", "UPmedya19!!!!" },
new string[] {"aledabuyuran", "UPmedya19!!!!" },
new string[] {"canguneybulbul", "UPmedya19!!!!" },
new string[] {"mahmutbilalbulend", "UPmedya19!!!!" },
new string[] {"salihazeynepbulent", "UPmedya19!!!!" },
new string[] {"melikedilarabuyukfirat", "UPmedya19!!!!" },
new string[] {"hayriyebuyukgungor", "UPmedya19!!!!" },
new string[] {"sebihabuyukozturk", "UPmedya19!!!!" },
new string[] {"mehmetcanakcaozoglu", "UPmedya19!!!!" },
new string[] {"mehmetenescanan", "UPmedya19!!!!" },
new string[] {"kurtbeycanbagi", "UPmedya19!!!!" },
new string[] {"mustafatahacanbek", "UPmedya19!!!!" },
new string[] {"senanurcandan", "UPmedya19!!!!" },
new string[] {"abdullahemirhancaner", "UPmedya19!!!!" },
new string[] {"mustafakeremcansu", "UPmedya19!!!!" },
new string[] {"doktoracanuyar", "UPmedya19!!!!" },
new string[] {"seyitceran", "UPmedya19!!!!" },
new string[] {"selmasimgeceylan", "UPmedya19!!!!" },
new string[] {"askimchiklyaukova", "UPmedya19!!!!" },
new string[] {"ozgurchoi", "UPmedya19!!!!" },
new string[] {"tugcecibooglu", "UPmedya19!!!!" },
new string[] {"ozerseckinciddi", "UPmedya19!!!!" },
new string[] {"balkincigerlioglu", "UPmedya19!!!!" },
new string[] {"yucelcivan", "UPmedya19!!!!" },
new string[] {"sansalcosan", "UPmedya19!!!!" },
new string[] {"oguzcancosandal", "UPmedya19!!!!" },
new string[] {"mayiscumali", "UPmedya19!!!!" },
new string[] {"busracuce", "UPmedya19!!!!" },
new string[] {"afraselcencagan", "UPmedya19!!!!" },
new string[] {"gonulcagatay", "UPmedya19!!!!" },
new string[] {"doganguncaglar", "UPmedya19!!!!" },
new string[] {"elifegecaglayan", "UPmedya19!!!!" },
new string[] {"ozencakan", "UPmedya19!!!!" },
new string[] {"dilhancakanel", "UPmedya19!!!!" },
new string[] {"maralcakici", "UPmedya19!!!!" },
new string[] {"mahirecalim", "UPmedya19!!!!" },
new string[] {"hacibayramufukcamas", "UPmedya19!!!!" },
new string[] {"oltuncanga", "UPmedya19!!!!" },
new string[] {"onelcapa", "UPmedya19!!!!" },
new string[] {"bayulkencaprak", "UPmedya19!!!!" },
new string[] {"dilserencarici", "UPmedya19!!!!" },
new string[] {"elifbeyzacark", "UPmedya19!!!!" },
new string[] {"elvancatal", "UPmedya19!!!!" },
new string[] {"esimcaylar", "UPmedya19!!!!" },
new string[] {"senacekmecelioglu", "UPmedya19!!!!" },
new string[] {"muhammeduzeyircekmeci", "UPmedya19!!!!" },
new string[] {"aydinmertcelebican", "UPmedya19!!!!" },
new string[] {"cagkancelenlioglu", "UPmedya19!!!!" },
new string[] {"zumracelik", "UPmedya19!!!!" },
new string[] {"bayarcelik", "UPmedya19!!!!" },
new string[] {"gonulgulcelikagi", "UPmedya19!!!!" },
new string[] {"ecepinarceliker", "UPmedya19!!!!" },
new string[] {"mehmettarikcelikkol", "UPmedya19!!!!" },
new string[] {"elifecerci", "UPmedya19!!!!" },
new string[] {"efecancetintas", "UPmedya19!!!!" },
new string[] {"ridvancikikci", "UPmedya19!!!!" },
new string[] {"haticegamzecinar", "UPmedya19!!!!" },
new string[] {"yansihilalcinaroglu", "UPmedya19!!!!" },
new string[] {"omaccingir", "UPmedya19!!!!" },
new string[] {"erhanciray", "UPmedya19!!!!" },
new string[] {"suhedacicekli", "UPmedya19!!!!" },
new string[] {"unkancini", "UPmedya19!!!!" },
new string[] {"ahmetgazicintan", "UPmedya19!!!!" },
new string[] {"seheriremcitfci", "UPmedya19!!!!" },
new string[] {"gurbuzcivici", "UPmedya19!!!!" },
new string[] {"zulalcolak", "UPmedya19!!!!" },
new string[] {"ozanegecomu", "UPmedya19!!!!" },
new string[] {"hilalebruconay", "UPmedya19!!!!" },
new string[] {"aybencorumlu", "UPmedya19!!!!" },
new string[] {"abdulbakicotur", "UPmedya19!!!!" },
new string[] {"nevacuhadar", "UPmedya19!!!!" },
new string[] {"oznurculhaoglu", "UPmedya19!!!!" },
new string[] {"olgundadalioglu", "UPmedya19!!!!" },
new string[] {"cagriatahandagar", "UPmedya19!!!!" },
new string[] {"ozalpdagbag", "UPmedya19!!!!" },
new string[] {"husneaysundal", "UPmedya19!!!!" },
new string[] {"aydonatdalkilic", "UPmedya19!!!!" },
new string[] {"ezgindalli", "UPmedya19!!!!" },
new string[] {"refiyesedadalyaprak", "UPmedya19!!!!" },
new string[] {"esaterdemdanis", "UPmedya19!!!!" },
new string[] {"ayseneslihandasdemir", "UPmedya19!!!!" },
new string[] {"fetullahdavutoglu", "UPmedya19!!!!" },
new string[] {"mertgorkemdayioglu", "UPmedya19!!!!" },
new string[] {"ergundegirmendereli", "UPmedya19!!!!" },
new string[] {"hulyadelichasan", "UPmedya19!!!!" },
new string[] {"dogaelifdelice", "UPmedya19!!!!" },
new string[] {"muhammedbazitdeliloglu", "UPmedya19!!!!" },
new string[] {"miracdemiroren", "UPmedya19!!!!" },
new string[] {"hureldemiriz", "UPmedya19!!!!" },
new string[] {"somerdemiroglu", "UPmedya19!!!!" },
new string[] {"ayselaysudemirsatan", "UPmedya19!!!!" },
new string[] {"mehmetkemaldengizek", "UPmedya19!!!!" },
new string[] {"alyadenizgunu", "UPmedya19!!!!" },
new string[] {"zeynepbusraderdemez", "UPmedya19!!!!" },
new string[] {"tubanurdereli", "UPmedya19!!!!" },
new string[] {"dalayderya", "UPmedya19!!!!" },
new string[] {"bedirdestereci", "UPmedya19!!!!" },
new string[] {"rumeysairemdevecel", "UPmedya19!!!!" },
new string[] {"osmansinandevrim", "UPmedya19!!!!" },
new string[] {"salihacanandivarci", "UPmedya19!!!!" },
new string[] {"sametemredikbas", "UPmedya19!!!!" },
new string[] {"haldundincturk", "UPmedya19!!!!" },
new string[] {"goncaguldiri", "UPmedya19!!!!" },
new string[] {"ziyadogramaci", "UPmedya19!!!!" },
new string[] {"zehrapelindoger", "UPmedya19!!!!" },
new string[] {"selimsharefdokulmez", "UPmedya19!!!!" },
new string[] {"firuzedonder", "UPmedya19!!!!" },
new string[] {"dorukdenizdoner", "UPmedya19!!!!" },
new string[] {"cisilzeynepdonmez", "UPmedya19!!!!" },
new string[] {"tugcedudu", "UPmedya19!!!!" },
new string[] {"enverdur", "UPmedya19!!!!" },
new string[] {"sanberdurak", "UPmedya19!!!!" },
new string[] {"birsendurmus", "UPmedya19!!!!" },
new string[] {"tacmindurmusoglu", "UPmedya19!!!!" },
new string[] {"karanalpdursun", "UPmedya19!!!!" },
new string[] {"oktemduymus", "UPmedya19!!!!" },
new string[] {"elanazdulgerbaki", "UPmedya19!!!!" },
new string[] {"fidandundar", "UPmedya19!!!!" },
new string[] {"barindusenkalkar", "UPmedya19!!!!" },
new string[] {"mehmetermanduzbayir", "UPmedya19!!!!" },
new string[] {"cemefeedes", "UPmedya19!!!!" },
new string[] {"eremedibalimp", "UPmedya19!!!!" },
new string[] {"volkaneyupefsin", "UPmedya19!!!!" },
new string[] {"ibrahimalptekinege", "UPmedya19!!!!" },
new string[] {"gungorerkinegeli", "UPmedya19!!!!" },
new string[] {"caginegin", "UPmedya19!!!!" },
new string[] {"alphanekercan", "UPmedya19!!!!" },
new string[] {"laleekrem", "UPmedya19!!!!" },
new string[] {"bagiscanelbasi", "UPmedya19!!!!" },
new string[] {"mertcemelicin", "UPmedya19!!!!" },
new string[] {"ahmetsenceremikoglu", "UPmedya19!!!!" },
new string[] {"akifeerbay", "UPmedya19!!!!" },
new string[] {"burcerbil", "UPmedya19!!!!" },
new string[] {"nadireerbul", "UPmedya19!!!!" },
new string[] {"huseyinzeydercoskun", "UPmedya19!!!!" },
new string[] {"aynurgulercument", "UPmedya19!!!!" },
new string[] {"samederek", "UPmedya19!!!!" },
new string[] {"cemozanerim", "UPmedya19!!!!" },
new string[] {"baharcemreerin", "UPmedya19!!!!" },
new string[] {"rekinerkek", "UPmedya19!!!!" },
new string[] {"huseyinserkanerkekli", "UPmedya19!!!!" },
new string[] {"ibrahimcandaserki", "UPmedya19!!!!" },
new string[] {"benizerkmen", "UPmedya19!!!!" },
new string[] {"hasanburakerkoc", "UPmedya19!!!!" },
new string[] {"selmanerkosan", "UPmedya19!!!!" },
new string[] {"hanifenurerkovan", "UPmedya19!!!!" },
new string[] {"alpereminerkus", "UPmedya19!!!!" },
new string[] {"elifkevsereroglu", "UPmedya19!!!!" },
new string[] {"abdullahmerterol", "UPmedya19!!!!" },
new string[] {"ciselersin", "UPmedya19!!!!" },
new string[] {"ilkinersoz", "UPmedya19!!!!" },
new string[] {"cantekinerten", "UPmedya19!!!!" },
new string[] {"onurkeremertepinar", "UPmedya19!!!!" },
new string[] {"ismaileneseruzun", "UPmedya19!!!!" },
new string[] {"hamideryildiz", "UPmedya19!!!!" },
new string[] {"tuncaeryilmaz", "UPmedya19!!!!" },
new string[] {"arslanerzurumlu", "UPmedya19!!!!" },
new string[] {"neslihanbusraesat", "UPmedya19!!!!" },
new string[] {"lutfiyesenaesen", "UPmedya19!!!!" },
new string[] {"belinesendemir", "UPmedya19!!!!" },
new string[] {"rukiyeesgin", "UPmedya19!!!!" },
new string[] {"islameshaqzada", "UPmedya19!!!!" },
new string[] {"batirayeski", "UPmedya19!!!!" },
new string[] {"suheylesvap", "UPmedya19!!!!" },
new string[] {"yargiyektaese", "UPmedya19!!!!" },
new string[] {"elzemevrenos", "UPmedya19!!!!" },
new string[] {"ilgazeyipisiren", "UPmedya19!!!!" },
new string[] {"ongareyyupoglu", "UPmedya19!!!!" },
new string[] {"faikezber", "UPmedya19!!!!" },
new string[] {"turanfahri", "UPmedya19!!!!" },
new string[] {"okbayfatih", "UPmedya19!!!!" },
new string[] {"latifefatin", "UPmedya19!!!!" },
new string[] {"eyuporhunfindik", "UPmedya19!!!!" },
new string[] {"irfananilfindikci", "UPmedya19!!!!" },
new string[] {"ertugfuruncuoglu", "UPmedya19!!!!" },
new string[] {"berhudangarip", "UPmedya19!!!!" },
new string[] {"nihangazitepe", "UPmedya19!!!!" },
new string[] {"meneksegeben", "UPmedya19!!!!" },
new string[] {"senizgebologlu", "UPmedya19!!!!" },
new string[] {"zeynepsenahangecioglu", "UPmedya19!!!!" },
new string[] {"hayrianilgeckin", "UPmedya19!!!!" },
new string[] {"muazzezecegemalmaz", "UPmedya19!!!!" },
new string[] {"keremcahitgencoglu", "UPmedya19!!!!" },
new string[] {"sadikcangezmis", "UPmedya19!!!!" },
new string[] {"resmiyeelifgirgin", "UPmedya19!!!!" },
new string[] {"nergizgilim", "UPmedya19!!!!" },
new string[] {"mehmetgokalpginovic", "UPmedya19!!!!" },
new string[] {"mehmetaligirgin", "UPmedya19!!!!" },
new string[] {"abdullahhalitgolba", "UPmedya19!!!!" },
new string[] {"tilbegoc", "UPmedya19!!!!" },
new string[] {"kubragocmen", "UPmedya19!!!!" },
new string[] {"kubilaygodek", "UPmedya19!!!!" },
new string[] {"busemgokceaslan", "UPmedya19!!!!" },
new string[] {"banuhangokcek", "UPmedya19!!!!" },
new string[] {"orgungokhan", "UPmedya19!!!!" },
new string[] {"melikegoksoy", "UPmedya19!!!!" },
new string[] {"yesimgolmes", "UPmedya19!!!!" },
new string[] {"nilufergonay", "UPmedya19!!!!" },
new string[] {"denizhangonul", "UPmedya19!!!!" },
new string[] {"suedagoreke", "UPmedya19!!!!" },
new string[] {"ersingorgulu", "UPmedya19!!!!" },
new string[] {"sahabettingorguner", "UPmedya19!!!!" },
new string[] {"ayseelifgorur", "UPmedya19!!!!" },
new string[] {"nazimberkegoven", "UPmedya19!!!!" },
new string[] {"meltemgoymen", "UPmedya19!!!!" },
new string[] {"abdulhalimguguk", "UPmedya19!!!!" },
new string[] {"gultenguducu", "UPmedya19!!!!" },
new string[] {"isinbikegulcan", "UPmedya19!!!!" },
new string[] {"vediagulcin", "UPmedya19!!!!" },
new string[] {"fatmasenaguldogus", "UPmedya19!!!!" },
new string[] {"omerokangulebakan", "UPmedya19!!!!" },
new string[] {"aybikegulec", "UPmedya19!!!!" },
new string[] {"bektasgulenc", "UPmedya19!!!!" },
new string[] {"emircanguleryuz", "UPmedya19!!!!" },
new string[] {"mertergulkan", "UPmedya19!!!!" },
new string[] {"sevgitutkugulluce", "UPmedya19!!!!" },
new string[] {"denktasgulsen", "UPmedya19!!!!" },
new string[] {"koksalgultas", "UPmedya19!!!!" },
new string[] {"hasanfahrigultepe", "UPmedya19!!!!" },
new string[] {"oymengumussoy", "UPmedya19!!!!" },
new string[] {"eylemgunduz", "UPmedya19!!!!" },
new string[] {"melekdilergunel", "UPmedya19!!!!" },
new string[] {"argunguneri", "UPmedya19!!!!" },
new string[] {"mehmetyektaguneyi", "UPmedya19!!!!" },
new string[] {"yaseminervaguntek", "UPmedya19!!!!" },
new string[] {"gunangural", "UPmedya19!!!!" },
new string[] {"osmancihangurdemir", "UPmedya19!!!!" },
new string[] {"okyanusgurel", "UPmedya19!!!!" },
new string[] {"mertalicangures", "UPmedya19!!!!" },
new string[] {"zeynepdogagurses", "UPmedya19!!!!" },
new string[] {"tarikguven", "UPmedya19!!!!" },
new string[] {"birgenguvener", "UPmedya19!!!!" },
new string[] {"ahmetkorhanguzel", "UPmedya19!!!!" },
new string[] {"manolyaguzeller", "UPmedya19!!!!" },
new string[] {"mustafaberkayguzeloglu", "UPmedya19!!!!" },
new string[] {"mehmetanilhacialioglu", "UPmedya19!!!!" },
new string[] {"ahmetfurkanhacilar", "UPmedya19!!!!" },
new string[] {"fazilethacioglu", "UPmedya19!!!!" },
new string[] {"kivilcimhadi", "UPmedya19!!!!" },
new string[] {"cisilhazalhafiz", "UPmedya19!!!!" },
new string[] {"ferayhakverdi", "UPmedya19!!!!" },
new string[] {"busranurhalacoglu", "UPmedya19!!!!" },
new string[] {"selinsilahalicilar", "UPmedya19!!!!" },
new string[] {"yeterhamamcioglu", "UPmedya19!!!!" },
new string[] {"ramazantarikhamarat", "UPmedya19!!!!" },
new string[] {"boranhamidi", "UPmedya19!!!!" },
new string[] {"tazikahilalhamzaoglu", "UPmedya19!!!!" },
new string[] {"aynurdilanhanci", "UPmedya19!!!!" },
new string[] {"aymanhangul", "UPmedya19!!!!" },
new string[] {"berrakharman", "UPmedya19!!!!" },
new string[] {"erkdehaharmankaya", "UPmedya19!!!!" },
new string[] {"perihanhaykir", "UPmedya19!!!!" },
new string[] {"turhanonurhirlak", "UPmedya19!!!!" },
new string[] {"furkanhizarcioglu", "UPmedya19!!!!" },
new string[] {"mustafaalihicyilmam", "UPmedya19!!!!" },
new string[] {"muhammedsefahilal", "UPmedya19!!!!" },
new string[] {"argunhilmi", "UPmedya19!!!!" },
new string[] {"fadikhimoglu", "UPmedya19!!!!" },
new string[] {"ahmethakkihirik", "UPmedya19!!!!" },
new string[] {"mustafasefahopaci", "UPmedya19!!!!" },
new string[] {"toykanhorata", "UPmedya19!!!!" },
new string[] {"selimehuner", "UPmedya19!!!!" },
new string[] {"denizcanilik", "UPmedya19!!!!" },
new string[] {"aysezeynebiricioglu", "UPmedya19!!!!" },
new string[] {"mustafafurkanisinay", "UPmedya19!!!!" },
new string[] {"sudeibrahim", "UPmedya19!!!!" },
new string[] {"gucluicten", "UPmedya19!!!!" },
new string[] {"katyailgezdi", "UPmedya19!!!!" },
new string[] {"halidilhan", "UPmedya19!!!!" },
new string[] {"nihalilisu", "UPmedya19!!!!" },
new string[] {"elifnisanimamoglu", "UPmedya19!!!!" },
new string[] {"emineselcenimre", "UPmedya19!!!!" },
new string[] {"tevfikinal", "UPmedya19!!!!" },
new string[] {"ibrahimkaganincekara", "UPmedya19!!!!" },
new string[] {"sidarinceoglu", "UPmedya19!!!!" },
new string[] {"nesliipcizade", "UPmedya19!!!!" },
new string[] {"ihsanvehbiipekoglu", "UPmedya19!!!!" },
new string[] {"necatiirsoy", "UPmedya19!!!!" },
new string[] {"zerinishakoglu", "UPmedya19!!!!" },
new string[] {"dursunkorelisgoren", "UPmedya19!!!!" },
new string[] {"ahusenisguzar", "UPmedya19!!!!" },
new string[] {"uzelkabatas", "UPmedya19!!!!" },
new string[] {"melisezgikabayuka", "UPmedya19!!!!" },
new string[] {"saziyekabukcu", "UPmedya19!!!!" },
new string[] {"berguzarkacaranoglu", "UPmedya19!!!!" },
new string[] {"omerfarukkadi", "UPmedya19!!!!" },
new string[] {"daghankadoglu", "UPmedya19!!!!" },
new string[] {"unzilekalfaoglu", "UPmedya19!!!!" },
new string[] {"sezerkalsin", "UPmedya19!!!!" },
new string[] {"sensoykalyoncu", "UPmedya19!!!!" },
new string[] {"necatikamisli", "UPmedya19!!!!" },
new string[] {"sahankandasoglu", "UPmedya19!!!!" },
new string[] {"necipfazilkanli", "UPmedya19!!!!" },
new string[] {"muharremkanmaz", "UPmedya19!!!!" },
new string[] {"zeynepfigenkantarci", "UPmedya19!!!!" },
new string[] {"cilaykapsiz", "UPmedya19!!!!" },
new string[] {"sunakaraaslanli", "UPmedya19!!!!" },
new string[] {"ahmetcankarabacak", "UPmedya19!!!!" },
new string[] {"asyasemakarabag", "UPmedya19!!!!" },
new string[] {"gulsenakarabiyik", "UPmedya19!!!!" },
new string[] {"fatmabusrakarabiyikli", "UPmedya19!!!!" },
new string[] {"arcakarabulut", "UPmedya19!!!!" },
new string[] {"abdullatifkaracabey", "UPmedya19!!!!" },
new string[] {"tugrakaracan", "UPmedya19!!!!" },
new string[] {"emirdogankaracay", "UPmedya19!!!!" },
new string[] {"halukbariskaracesme", "UPmedya19!!!!" },
new string[] {"seyitahmetkaradag", "UPmedya19!!!!" },
new string[] {"cevzakaradalan", "UPmedya19!!!!" },
new string[] {"mustafaemirkarademir", "UPmedya19!!!!" },
new string[] {"ilgarpamirkaraismail", "UPmedya19!!!!" },
new string[] {"serenkarakan", "UPmedya19!!!!" },
new string[] {"busrahazalkarakaplan", "UPmedya19!!!!" },
new string[] {"nacikarakaya", "UPmedya19!!!!" },
new string[] {"oguzselimkarakelle", "UPmedya19!!!!" },
new string[] {"faikaltugkarakoca", "UPmedya19!!!!" },
new string[] {"dincolkaralar", "UPmedya19!!!!" },
new string[] {"ceyhunkadirkaramollaoglu", "UPmedya19!!!!" },
new string[] {"tayyibekaranisoglu", "UPmedya19!!!!" },
new string[] {"hayriyegulkararti", "UPmedya19!!!!" },
new string[] {"gulsanemkarasapan", "UPmedya19!!!!" },
new string[] {"yeldakardas", "UPmedya19!!!!" },
new string[] {"kuntayyigitkarga", "UPmedya19!!!!" },
new string[] {"ahmetberkekargin", "UPmedya19!!!!" },
new string[] {"kivanckasaci", "UPmedya19!!!!" },
new string[] {"virakasemllar", "UPmedya19!!!!" },
new string[] {"orselkaska", "UPmedya19!!!!" },
new string[] {"esmaecekavak", "UPmedya19!!!!" },
new string[] {"benekkavas", "UPmedya19!!!!" },
new string[] {"halenurkavasoglu", "UPmedya19!!!!" },
new string[] {"umitkavukcu", "UPmedya19!!!!" },
new string[] {"ishakkayacan", "UPmedya19!!!!" },
new string[] {"ibrahimkayahan", "UPmedya19!!!!" },
new string[] {"odulkayali", "UPmedya19!!!!" },
new string[] {"egesarpkayar", "UPmedya19!!!!" },
new string[] {"mahmutonurkayhan", "UPmedya19!!!!" },
new string[] {"mimozakaynamis", "UPmedya19!!!!" },
new string[] {"cemilekazici", "UPmedya19!!!!" },
new string[] {"belitkece", "UPmedya19!!!!" },
new string[] {"aslinurkefal", "UPmedya19!!!!" },
new string[] {"acunkeles", "UPmedya19!!!!" },
new string[] {"behcetkutaykerem", "UPmedya19!!!!" },
new string[] {"aysemervekerigan", "UPmedya19!!!!" },
new string[] {"behinkerimov", "UPmedya19!!!!" },
new string[] {"fatmahilalkesbic", "UPmedya19!!!!" },
new string[] {"nunkesgin", "UPmedya19!!!!" },
new string[] {"ahmetmehdikeskin", "UPmedya19!!!!" },
new string[] {"mehpareketeci", "UPmedya19!!!!" },
new string[] {"muhammedikbalkevkir", "UPmedya19!!!!" },
new string[] {"alaatinkilcadir", "UPmedya19!!!!" },
new string[] {"hamitkildir", "UPmedya19!!!!" },
new string[] {"muktedirkilincarslan", "UPmedya19!!!!" },
new string[] {"onurabdikina", "UPmedya19!!!!" },
new string[] {"lokmankirbiyik", "UPmedya19!!!!" },
new string[] {"mertkirgiz", "UPmedya19!!!!" },
new string[] {"gulenaykiris", "UPmedya19!!!!" },
new string[] {"mursidekirkpinar", "UPmedya19!!!!" },
new string[] {"furkanfatihkirmizi", "UPmedya19!!!!" },
new string[] {"haticebusrakirtas", "UPmedya19!!!!" },
new string[] {"yasarfatiheneskirtay", "UPmedya19!!!!" },
new string[] {"parlakiryayla", "UPmedya19!!!!" },
new string[] {"gulcekivilcim", "UPmedya19!!!!" },
new string[] {"yasinburakkizil", "UPmedya19!!!!" },
new string[] {"alimkizilboga", "UPmedya19!!!!" },
new string[] {"iscankizilca", "UPmedya19!!!!" },
new string[] {"evrenburakkizilirmak", "UPmedya19!!!!" },
new string[] {"ozgegizemkizilkaya", "UPmedya19!!!!" },
new string[] {"dilsadnurkiziltug", "UPmedya19!!!!" },
new string[] {"eneskizmaz", "UPmedya19!!!!" },
new string[] {"yalcinkilmen", "UPmedya19!!!!" },
new string[] {"aliaydinkirezcik", "UPmedya19!!!!" },
new string[] {"skaancankisial", "UPmedya19!!!!" },
new string[] {"maisamkisin", "UPmedya19!!!!" },
new string[] {"mehmethankocabas", "UPmedya19!!!!" },
new string[] {"irazhakkinakocabiyik", "UPmedya19!!!!" },
new string[] {"yigithankocademir", "UPmedya19!!!!" },
new string[] {"iremcerenkocak", "UPmedya19!!!!" },
new string[] {"yusufsuhakocbaba", "UPmedya19!!!!" },
new string[] {"iptalkocsoy", "UPmedya19!!!!" },
new string[] {"abdulsametkonakoglu", "UPmedya19!!!!" },
new string[] {"mehmetbariskondakcioglu", "UPmedya19!!!!" },
new string[] {"ahenkkontaci", "UPmedya19!!!!" },
new string[] {"hayatkonyar", "UPmedya19!!!!" },
new string[] {"yigitalperenkoparan", "UPmedya19!!!!" },
new string[] {"gunerkorkmazcan", "UPmedya19!!!!" },
new string[] {"berfuiremkoskulu", "UPmedya19!!!!" },
new string[] {"ilkekotan", "UPmedya19!!!!" },
new string[] {"aliozankovanci", "UPmedya19!!!!" },
new string[] {"fatmanurkoytak", "UPmedya19!!!!" },
new string[] {"ibrahimfehmikoyunsev", "UPmedya19!!!!" },
new string[] {"aslinazkozakcioglu", "UPmedya19!!!!" },
new string[] {"ataalpkocer", "UPmedya19!!!!" },
new string[] {"macidekokcu", "UPmedya19!!!!" },
new string[] {"mustafakoken", "UPmedya19!!!!" },
new string[] {"aybarkormukcu", "UPmedya19!!!!" },
new string[] {"sahinkose", "UPmedya19!!!!" },
new string[] {"tunckoybasi", "UPmedya19!!!!" },
new string[] {"ruveydakuday", "UPmedya19!!!!" },
new string[] {"gurolkudu", "UPmedya19!!!!" },
new string[] {"chakankukaraci", "UPmedya19!!!!" },
new string[] {"eliskul", "UPmedya19!!!!" },
new string[] {"selmakuloglu", "UPmedya19!!!!" },
new string[] {"huseyinkumru", "UPmedya19!!!!" },
new string[] {"acaroguztankundakci", "UPmedya19!!!!" },
new string[] {"guneykunter", "UPmedya19!!!!" },
new string[] {"ozgesilakuntman", "UPmedya19!!!!" },
new string[] {"sevalkurtan", "UPmedya19!!!!" },
new string[] {"bernakurtulus", "UPmedya19!!!!" },
new string[] {"seriferkamkutanoglu", "UPmedya19!!!!" },
new string[] {"meliketamarakutlay", "UPmedya19!!!!" },
new string[] {"aycagkucukbey", "UPmedya19!!!!" },
new string[] {"sadiyekucukkase", "UPmedya19!!!!" },
new string[] {"alikucukler", "UPmedya19!!!!" },
new string[] {"nigarkulahlioglu", "UPmedya19!!!!" },
new string[] {"gulbenkurk", "UPmedya19!!!!" },
new string[] {"ayseferhundekurkcu", "UPmedya19!!!!" },
new string[] {"eralpkurum", "UPmedya19!!!!" },
new string[] {"alperenkusku", "UPmedya19!!!!" },
new string[] {"zehrasenamadran", "UPmedya19!!!!" },
new string[] {"gunduzmagden", "UPmedya19!!!!" },
new string[] {"osmanemremaldar", "UPmedya19!!!!" },
new string[] {"kubatmalekiravasan", "UPmedya19!!!!" },
new string[] {"baharelcinmammadov", "UPmedya19!!!!" },
new string[] {"nuelifmardanlou", "UPmedya19!!!!" },
new string[] {"mehmeterenmasaraci", "UPmedya19!!!!" },
new string[] {"melismasir", "UPmedya19!!!!" },
new string[] {"fatimamatur", "UPmedya19!!!!" },
new string[] {"karacamaydagil", "UPmedya19!!!!" },
new string[] {"zaferenginmemisler", "UPmedya19!!!!" },
new string[] {"duygunmenguc", "UPmedya19!!!!" },
new string[] {"havagulmercimekci", "UPmedya19!!!!" },
new string[] {"ariffurkanmerdan", "UPmedya19!!!!" },
new string[] {"halitcanmert", "UPmedya19!!!!" },
new string[] {"pertevmetin", "UPmedya19!!!!" },
new string[] {"selismezarci", "UPmedya19!!!!" },
new string[] {"galipmirzanli", "UPmedya19!!!!" },
new string[] {"tulaytugcemisoglu", "UPmedya19!!!!" },
new string[] {"ahusemohamed", "UPmedya19!!!!" },
new string[] {"barbarosmollaametali", "UPmedya19!!!!" },
new string[] {"lawrencetezohmorbenli", "UPmedya19!!!!" },
new string[] {"gorkemmorelli", "UPmedya19!!!!" },
new string[] {"abdurahmanmorgul", "UPmedya19!!!!" },
new string[] {"zulcenahmortepe", "UPmedya19!!!!" },
new string[] {"saadetnurmumcu", "UPmedya19!!!!" },
new string[] {"hasangurkanmuratoglu", "UPmedya19!!!!" },
new string[] {"sehmusmursal", "UPmedya19!!!!" },
new string[] {"berkanmusaoglu", "UPmedya19!!!!" },
new string[] {"erselmuslu", "UPmedya19!!!!" },
new string[] {"batugmutman", "UPmedya19!!!!" },
new string[] {"dilsumunif", "UPmedya19!!!!" },
new string[] {"erdogannalbant", "UPmedya19!!!!" },
new string[] {"batinalbantoglu", "UPmedya19!!!!" },
new string[] {"turkannalcaci", "UPmedya19!!!!" },
new string[] {"gulpinarnamdar", "UPmedya19!!!!" },
new string[] {"gokcinnamli", "UPmedya19!!!!" },
new string[] {"ulkernayman", "UPmedya19!!!!" },
new string[] {"eslemnerkis", "UPmedya19!!!!" },
new string[] {"nazliozumnisanci", "UPmedya19!!!!" },
new string[] {"alkiznumanoglu", "UPmedya19!!!!" },
new string[] {"nimetocalan", "UPmedya19!!!!" },
new string[] {"ismailegecanocar", "UPmedya19!!!!" },
new string[] {"kameroduncu", "UPmedya19!!!!" },
new string[] {"gencaloguz", "UPmedya19!!!!" },
new string[] {"kursatoguzfp", "UPmedya19!!!!" },
new string[] {"irembasakoguzhan", "UPmedya19!!!!" },
new string[] {"ulascanokan", "UPmedya19!!!!" },
new string[] {"tunahanokatan", "UPmedya19!!!!" },
new string[] {"izelokcu", "UPmedya19!!!!" },
new string[] {"elizokkaya", "UPmedya19!!!!" },
new string[] {"cisilokumus", "UPmedya19!!!!" },
new string[] {"keremcanonus", "UPmedya19!!!!" },
new string[] {"keremcanoraloglu", "UPmedya19!!!!" },
new string[] {"taliporhan", "UPmedya19!!!!" },
new string[] {"besteorhon", "UPmedya19!!!!" },
new string[] {"ismetorman", "UPmedya19!!!!" },
new string[] {"mustafaboraozgun", "UPmedya19!!!!" },
new string[] {"oganocal", "UPmedya19!!!!" },
new string[] {"ahmetcihatogredik", "UPmedya19!!!!" },
new string[] {"vahideokmen", "UPmedya19!!!!" },
new string[] {"murtazaolmezler", "UPmedya19!!!!" },
new string[] {"gonenonder", "UPmedya19!!!!" },
new string[] {"zeyneptubaonen", "UPmedya19!!!!" },
new string[] {"gunkutonoglu", "UPmedya19!!!!" },
new string[] {"farukdogukanoreroglu", "UPmedya19!!!!" },
new string[] {"gunyolufukorge", "UPmedya19!!!!" },
new string[] {"selimcanors", "UPmedya19!!!!" },
new string[] {"raifaniloter", "UPmedya19!!!!" },
new string[] {"okandenizovul", "UPmedya19!!!!" },
new string[] {"mustafaselmanoyus", "UPmedya19!!!!" },
new string[] {"ayseloz", "UPmedya19!!!!" },
new string[] {"ajlanozakyol", "UPmedya19!!!!" },
new string[] {"ayhanfurkanozar", "UPmedya19!!!!" },
new string[] {"ebrueceozata", "UPmedya19!!!!" },
new string[] {"berfinelifozay", "UPmedya19!!!!" },
new string[] {"muhammetozaydin", "UPmedya19!!!!" },
new string[] {"ardaalanozayral", "UPmedya19!!!!" },
new string[] {"isilayozbey", "UPmedya19!!!!" },
new string[] {"selaleozbir", "UPmedya19!!!!" },
new string[] {"oktayemirozcan", "UPmedya19!!!!" },
new string[] {"gunizozdel", "UPmedya19!!!!" },
new string[] {"murathanozdil", "UPmedya19!!!!" },
new string[] {"kadirrozdincer", "UPmedya19!!!!" },
new string[] {"anilseckinozelci", "UPmedya19!!!!" },
new string[] {"dilaynurozer", "UPmedya19!!!!" },
new string[] {"semsiyigitozev", "UPmedya19!!!!" },
new string[] {"ilayozgenc", "UPmedya19!!!!" },
new string[] {"bediaozgenoglu", "UPmedya19!!!!" },
new string[] {"kadiranilozgezgin", "UPmedya19!!!!" },
new string[] {"ecemozgul", "UPmedya19!!!!" },
new string[] {"girayozgumus", "UPmedya19!!!!" },
new string[] {"abdulsamedozgur", "UPmedya19!!!!" },
new string[] {"tenduozgurun", "UPmedya19!!!!" },
new string[] {"eminetugceozirk", "UPmedya19!!!!" },
new string[] {"mehmetyusaozkol", "UPmedya19!!!!" },
new string[] {"egehanozkok", "UPmedya19!!!!" },
new string[] {"mustafaerenozkul", "UPmedya19!!!!" },
new string[] {"iremnurozmez", "UPmedya19!!!!" },
new string[] {"fahirozpak", "UPmedya19!!!!" },
new string[] {"aliahmetozpercin", "UPmedya19!!!!" },
new string[] {"eyupcanozperk", "UPmedya19!!!!" },
new string[] {"mervenurozpolat", "UPmedya19!!!!" },
new string[] {"muhammerozsoydan", "UPmedya19!!!!" },
new string[] {"arkadasnecatioztas", "UPmedya19!!!!" },
new string[] {"gunaydinozteker", "UPmedya19!!!!" },
new string[] {"zuleyhaoztemel", "UPmedya19!!!!" },
new string[] {"mustafaoguzhanoztunc", "UPmedya19!!!!" },
new string[] {"okcanozturk", "UPmedya19!!!!" },
new string[] {"muhammedeminozuberk", "UPmedya19!!!!" },
new string[] {"gamzenurpadak", "UPmedya19!!!!" },
new string[] {"muhammedkerempak", "UPmedya19!!!!" },
new string[] {"zeynepecehanpakdemirli", "UPmedya19!!!!" },
new string[] {"safakpakdil", "UPmedya19!!!!" },
new string[] {"sukranpakkan", "UPmedya19!!!!" },
new string[] {"altaypaksoy", "UPmedya19!!!!" },
new string[] {"hicretpalanko", "UPmedya19!!!!" },
new string[] {"nusretpalut", "UPmedya19!!!!" },
new string[] {"omerpamukcu", "UPmedya19!!!!" },
new string[] {"mehmetziyapancar", "UPmedya19!!!!" },
new string[] {"aysuparlak", "UPmedya19!!!!" },
new string[] {"cenappasolar", "UPmedya19!!!!" },
new string[] {"atapazar", "UPmedya19!!!!" },
new string[] {"sabanpehlevan", "UPmedya19!!!!" },
new string[] {"humapehlivan", "UPmedya19!!!!" },
new string[] {"ekinesmepehlivanli", "UPmedya19!!!!" },
new string[] {"mehtappehlivanoglu", "UPmedya19!!!!" },
new string[] {"mehmetsaidpekdogdu", "UPmedya19!!!!" },
new string[] {"cihadpektemek", "UPmedya19!!!!" },
new string[] {"senaypiristina", "UPmedya19!!!!" },
new string[] {"umranpocan", "UPmedya19!!!!" },
new string[] {"evrenpomay", "UPmedya19!!!!" },
new string[] {"kevserportakal", "UPmedya19!!!!" },
new string[] {"ziynetposbiyik", "UPmedya19!!!!" },
new string[] {"muhammedkutayposlu", "UPmedya19!!!!" },
new string[] {"efganpuca", "UPmedya19!!!!" },
new string[] {"baharmervepurcu", "UPmedya19!!!!" },
new string[] {"dilaraaysimramis", "UPmedya19!!!!" },
new string[] {"tomurcukrauf", "UPmedya19!!!!" },
new string[] {"simaviremzi", "UPmedya19!!!!" },
new string[] {"esmaedarevan", "UPmedya19!!!!" },
new string[] {"utkurona", "UPmedya19!!!!" },
new string[] {"nurselirusan", "UPmedya19!!!!" },
new string[] {"urcuksaatciler", "UPmedya19!!!!" },
new string[] {"cagataysabah", "UPmedya19!!!!" },
new string[] {"niyaziumutsabri", "UPmedya19!!!!" },
new string[] {"caglasacak", "UPmedya19!!!!" },
new string[] {"ayseberresadak", "UPmedya19!!!!" },
new string[] {"aligurelsadiklar", "UPmedya19!!!!" },
new string[] {"tayyipsadikoglu", "UPmedya19!!!!" },
new string[] {"nesatsadri", "UPmedya19!!!!" },
new string[] {"ferudunsaf", "UPmedya19!!!!" },
new string[] {"aysesalihasakarya", "UPmedya19!!!!" },
new string[] {"emrecansakaryali", "UPmedya19!!!!" },
new string[] {"omersefasaltuk", "UPmedya19!!!!" },
new string[] {"ahmetenessamanci", "UPmedya19!!!!" },
new string[] {"aliizzeddinsamar", "UPmedya19!!!!" },
new string[] {"fatmaserrasami", "UPmedya19!!!!" },
new string[] {"arcansaparca", "UPmedya19!!!!" },
new string[] {"gunnazsar", "UPmedya19!!!!" },
new string[] {"simgenursaracgil", "UPmedya19!!!!" },
new string[] {"nesringokcesaraclar", "UPmedya19!!!!" },
new string[] {"ayseisilsaray", "UPmedya19!!!!" },
new string[] {"nuecesarialtun", "UPmedya19!!!!" },
new string[] {"muhteremsarioglu", "UPmedya19!!!!" },
new string[] {"esengulsariteke", "UPmedya19!!!!" },
new string[] {"cansunursavca", "UPmedya19!!!!" },
new string[] {"necmettinsaydam", "UPmedya19!!!!" },
new string[] {"melikenursultansaydan", "UPmedya19!!!!" },
new string[] {"ayciceksaygin", "UPmedya19!!!!" },
new string[] {"muhammetfatihsayici", "UPmedya19!!!!" },
new string[] {"orkidesayil", "UPmedya19!!!!" },
new string[] {"ozgeelifsayrac", "UPmedya19!!!!" },
new string[] {"refiasazak", "UPmedya19!!!!" },
new string[] {"yaseminbaharschmitz", "UPmedya19!!!!" },
new string[] {"minasel", "UPmedya19!!!!" },
new string[] {"servetecenazselcuk", "UPmedya19!!!!" },
new string[] {"sevdenurselvi", "UPmedya19!!!!" },
new string[] {"abdullahfurkansenturk", "UPmedya19!!!!" },
new string[] {"olcasevcan", "UPmedya19!!!!" },
new string[] {"nebisever", "UPmedya19!!!!" },
new string[] {"yaseminsevigen", "UPmedya19!!!!" },
new string[] {"gunayseydaoglu", "UPmedya19!!!!" },
new string[] {"zuleyhaseyfi", "UPmedya19!!!!" },
new string[] {"tunayseyhan", "UPmedya19!!!!" },
new string[] {"tanjuseymen", "UPmedya19!!!!" },
new string[] {"muhammedsaitseytin", "UPmedya19!!!!" },
new string[] {"mehmetakifsirac", "UPmedya19!!!!" },
new string[] {"kaankubilaysimavli", "UPmedya19!!!!" },
new string[] {"aysegulsobaci", "UPmedya19!!!!" },
new string[] {"canelsofyalioglu", "UPmedya19!!!!" },
new string[] {"rabiakubrasolak", "UPmedya19!!!!" },
new string[] {"ikbalsongur", "UPmedya19!!!!" },
new string[] {"esatsoyadi", "UPmedya19!!!!" },
new string[] {"yunusgokersoylu", "UPmedya19!!!!" },
new string[] {"kanaatsoyulmaz", "UPmedya19!!!!" },
new string[] {"cengizhansokel", "UPmedya19!!!!" },
new string[] {"gencaysoker", "UPmedya19!!!!" },
new string[] {"gazanfersoylemez", "UPmedya19!!!!" },
new string[] {"dorukhansozeri", "UPmedya19!!!!" },
new string[] {"hesnaezgisozuer", "UPmedya19!!!!" },
new string[] {"ilknursozumcetin", "UPmedya19!!!!" },
new string[] {"firuzsu", "UPmedya19!!!!" },
new string[] {"hasangokaysugoturen", "UPmedya19!!!!" },
new string[] {"guzaysular", "UPmedya19!!!!" },
new string[] {"ozgunmertsuna", "UPmedya19!!!!" },
new string[] {"iparsuyunu", "UPmedya19!!!!" },
new string[] {"guralsuhan", "UPmedya19!!!!" },
new string[] {"nazberilsuleymanzade", "UPmedya19!!!!" },
new string[] {"irissureyya", "UPmedya19!!!!" },
new string[] {"gulselinsurmeli", "UPmedya19!!!!" },
new string[] {"alpersadi", "UPmedya19!!!!" },
new string[] {"abbassahabettinoglu", "UPmedya19!!!!" },
new string[] {"nugayesahin", "UPmedya19!!!!" },
new string[] {"buraktansahingoz", "UPmedya19!!!!" },
new string[] {"efemustafasakarcan", "UPmedya19!!!!" },
new string[] {"behiyesamlioglu", "UPmedya19!!!!" },
new string[] {"yagmurhelinsarkisla", "UPmedya19!!!!" },
new string[] {"aslicansekercioglu", "UPmedya19!!!!" },
new string[] {"cigdemsekeryan", "UPmedya19!!!!" },
new string[] {"taykutsenozen", "UPmedya19!!!!" },
new string[] {"fehimesuhedasenbas", "UPmedya19!!!!" },
new string[] {"oguncsencan", "UPmedya19!!!!" },
new string[] {"gurkansendag", "UPmedya19!!!!" },
new string[] {"sezanursendiller", "UPmedya19!!!!" },
new string[] {"sehersengul", "UPmedya19!!!!" },
new string[] {"nejatsenocak", "UPmedya19!!!!" },
new string[] {"yelizsenyurd", "UPmedya19!!!!" },
new string[] {"alitarikserbetci", "UPmedya19!!!!" },
new string[] {"adaseref", "UPmedya19!!!!" },
new string[] {"yunusemreserifoglu", "UPmedya19!!!!" },
new string[] {"melikedenizsevkin", "UPmedya19!!!!" },
new string[] {"mehvestabak", "UPmedya19!!!!" },
new string[] {"furkanalicantabanli", "UPmedya19!!!!" },
new string[] {"aykantabir", "UPmedya19!!!!" },
new string[] {"ahmetutkutac", "UPmedya19!!!!" },
new string[] {"dilaratacgin", "UPmedya19!!!!" },
new string[] {"miracayberktahir", "UPmedya19!!!!" },
new string[] {"kardelentahmazoglu", "UPmedya19!!!!" },
new string[] {"pinargultalantemur", "UPmedya19!!!!" },
new string[] {"areltalas", "UPmedya19!!!!" },
new string[] {"aysegulbegumtanbasi", "UPmedya19!!!!" },
new string[] {"farshadtanis", "UPmedya19!!!!" },
new string[] {"guzinduygutanrikulu", "UPmedya19!!!!" },
new string[] {"ebruummuhantarakci", "UPmedya19!!!!" },
new string[] {"numantarhan", "UPmedya19!!!!" },
new string[] {"celikertarlakazan", "UPmedya19!!!!" },
new string[] {"seventas", "UPmedya19!!!!" },
new string[] {"balatasak", "UPmedya19!!!!" },
new string[] {"kokertascioglu", "UPmedya19!!!!" },
new string[] {"batughantasgin", "UPmedya19!!!!" },
new string[] {"guventasli", "UPmedya19!!!!" },
new string[] {"ecegultasyurek", "UPmedya19!!!!" },
new string[] {"beyzanurtatli", "UPmedya19!!!!" },
new string[] {"keremardatatlisu", "UPmedya19!!!!" },
new string[] {"abdussamettayan", "UPmedya19!!!!" },
new string[] {"tilbesunaytayfun", "UPmedya19!!!!" },
new string[] {"ismailtazegul", "UPmedya19!!!!" },
new string[] {"ogurtecer", "UPmedya19!!!!" },
new string[] {"aktanteker", "UPmedya19!!!!" },
new string[] {"ahmetbugratekin", "UPmedya19!!!!" },
new string[] {"denizhaleteksan", "UPmedya19!!!!" },
new string[] {"umutsalihtektas", "UPmedya19!!!!" },
new string[] {"isiltantekten", "UPmedya19!!!!" },
new string[] {"erdemtemizer", "UPmedya19!!!!" },
new string[] {"atalayfurkantenim", "UPmedya19!!!!" },
new string[] {"alialptercan", "UPmedya19!!!!" },
new string[] {"sabihaesraterzi", "UPmedya19!!!!" },
new string[] {"yakupcantetik", "UPmedya19!!!!" },
new string[] {"talyatezmen", "UPmedya19!!!!" },
new string[] {"tugbanurtiftikci", "UPmedya19!!!!" },
new string[] {"aktactogay", "UPmedya19!!!!" },
new string[] {"ahucantogan", "UPmedya19!!!!" },
new string[] {"saimesuratokac", "UPmedya19!!!!" },
new string[] {"dogcantokali", "UPmedya19!!!!" },
new string[] {"bilhantokatlioglu", "UPmedya19!!!!" },
new string[] {"muhammedbilaltokdogan", "UPmedya19!!!!" },
new string[] {"sukruozumcantoker", "UPmedya19!!!!" },
new string[] {"ecenurtokgoz", "UPmedya19!!!!" },
new string[] {"baysaltolunay", "UPmedya19!!!!" },
new string[] {"mugetopal", "UPmedya19!!!!" },
new string[] {"dilsahtopalan", "UPmedya19!!!!" },
new string[] {"salihatopoyan", "UPmedya19!!!!" },
new string[] {"tarcantoptan", "UPmedya19!!!!" },
new string[] {"ruyasutorgutalp", "UPmedya19!!!!" },
new string[] {"gulsendilantorol", "UPmedya19!!!!" },
new string[] {"velittoygar", "UPmedya19!!!!" },
new string[] {"perkertufan", "UPmedya19!!!!" },
new string[] {"lerzantugrul", "UPmedya19!!!!" },
new string[] {"nuetugmen", "UPmedya19!!!!" },
new string[] {"yasaremretuncay", "UPmedya19!!!!" },
new string[] {"aybukeaycaturna", "UPmedya19!!!!" },
new string[] {"muhammetmustafaturul", "UPmedya19!!!!" },
new string[] {"lalezarturunc", "UPmedya19!!!!" },
new string[] {"iyilemtudes", "UPmedya19!!!!" },
new string[] {"istemifurkantufekci", "UPmedya19!!!!" },
new string[] {"ilseltufekcioglu", "UPmedya19!!!!" },
new string[] {"muhammedcanturkmenoglu", "UPmedya19!!!!" },
new string[] {"mebruketurkoglu", "UPmedya19!!!!" },
new string[] {"ummugulsumtut", "UPmedya19!!!!" },
new string[] {"gokborimertubay", "UPmedya19!!!!" },
new string[] {"zeynepneslihanucanok", "UPmedya19!!!!" },
new string[] {"malikucar", "UPmedya19!!!!" },
new string[] {"umutmertucma", "UPmedya19!!!!" },
new string[] {"enginsuugur", "UPmedya19!!!!" },
new string[] {"mervegululas", "UPmedya19!!!!" },
new string[] {"ugurulug", "UPmedya19!!!!" },
new string[] {"canerhazaruluhan", "UPmedya19!!!!" },
new string[] {"aysimulupinar", "UPmedya19!!!!" },
new string[] {"arifegulbizulusoy", "UPmedya19!!!!" },
new string[] {"haticebernaulutas", "UPmedya19!!!!" },
new string[] {"kuntayurganci", "UPmedya19!!!!" },
new string[] {"berraurgancioglu", "UPmedya19!!!!" },
new string[] {"zehranazusanmaz", "UPmedya19!!!!" },
new string[] {"ahuelausluer", "UPmedya19!!!!" },
new string[] {"bedriyeserayusta", "UPmedya19!!!!" },
new string[] {"alpdoraustabasi", "UPmedya19!!!!" },
new string[] {"gulumseusumi", "UPmedya19!!!!" },
new string[] {"enginugurusak", "UPmedya19!!!!" },
new string[] {"gizemnuruyu", "UPmedya19!!!!" },
new string[] {"kemaltolgauz", "UPmedya19!!!!" },
new string[] {"tahsinuzun", "UPmedya19!!!!" },
new string[] {"ugurcanuzundonekoglu", "UPmedya19!!!!" },
new string[] {"arsunuzunirmak", "UPmedya19!!!!" },
new string[] {"ozgecanucler", "UPmedya19!!!!" },
new string[] {"siddikauctas", "UPmedya19!!!!" },
new string[] {"imranmusaviulgey", "UPmedya19!!!!" },
new string[] {"ebrarunay", "UPmedya19!!!!" },
new string[] {"acilayunlu", "UPmedya19!!!!" },
new string[] {"muzehherzeynepunlu", "UPmedya19!!!!" },
new string[] {"aybirgenurkmezturk", "UPmedya19!!!!" },
new string[] {"akifuskent", "UPmedya19!!!!" },
new string[] {"volkanustbas", "UPmedya19!!!!" },
new string[] {"ozmenustunel", "UPmedya19!!!!" },
new string[] {"gulenderusenmez", "UPmedya19!!!!" },
new string[] {"muzafferuzar", "UPmedya19!!!!" },
new string[] {"medihaburcuvanli", "UPmedya19!!!!" },
new string[] {"sulhadinvarli", "UPmedya19!!!!" },
new string[] {"buketyildiz", "UPmedya19!!!!" },
new string[] {"serifyakupoglu", "UPmedya19!!!!" },
new string[] {"senasimayyalcinkaya", "UPmedya19!!!!" },
new string[] {"mumunenihanyalcintas", "UPmedya19!!!!" },
new string[] {"edisyalmac", "UPmedya19!!!!" },
new string[] {"alagulyalman", "UPmedya19!!!!" },
new string[] {"nazimbircanyalova", "UPmedya19!!!!" },
new string[] {"ekinegeyamanoglu", "UPmedya19!!!!" },
new string[] {"aysemelisayanik", "UPmedya19!!!!" },
new string[] {"anilgorkemyapar", "UPmedya19!!!!" },
new string[] {"cavityaprak", "UPmedya19!!!!" },
new string[] {"gulsahyarbas", "UPmedya19!!!!" },
new string[] {"isiltiyardimci", "UPmedya19!!!!" },
new string[] {"aysecansuyasa", "UPmedya19!!!!" },
new string[] {"muhammedaliduranyasin", "UPmedya19!!!!" },
new string[] {"nurullahyasin", "UPmedya19!!!!" },
new string[] {"nuvityavaser", "UPmedya19!!!!" },
new string[] {"taneryay", "UPmedya19!!!!" },
new string[] {"sezenyayla", "UPmedya19!!!!" },
new string[] {"tunahansalihyazicigil", "UPmedya19!!!!" },
new string[] {"raifyazicioglu", "UPmedya19!!!!" },
new string[] {"dilarazeynepyeksan", "UPmedya19!!!!" },
new string[] {"muhammedenesyel", "UPmedya19!!!!" },
new string[] {"busrahilalyelegen", "UPmedya19!!!!" },
new string[] {"meryemsumeyyeyeniceli", "UPmedya19!!!!" },
new string[] {"sayanyeniev", "UPmedya19!!!!" },
new string[] {"aykutyerlikaya", "UPmedya19!!!!" },
new string[] {"ilkyazyerliyurt", "UPmedya19!!!!" },
new string[] {"gulsenyerzhan", "UPmedya19!!!!" },
new string[] {"nurettinhazaryesilcimen", "UPmedya19!!!!" },
new string[] {"alifurkanyesilova", "UPmedya19!!!!" },
new string[] {"kolcakyikilmazsoy", "UPmedya19!!!!" },
new string[] {"selenelifyildirimer", "UPmedya19!!!!" },
new string[] {"azelyayildizdoken", "UPmedya19!!!!" },
new string[] {"ibrahimenginyildizoglu", "UPmedya19!!!!" },
new string[] {"sadriyirmibescik", "UPmedya19!!!!" },
new string[] {"enessaidyolcu", "UPmedya19!!!!" },
new string[] {"eseryorgun", "UPmedya19!!!!" },
new string[] {"selcenyorulmaz", "UPmedya19!!!!" },
new string[] {"alaaddinyondem", "UPmedya19!!!!" },
new string[] {"jiyanyoruten", "UPmedya19!!!!" },
new string[] {"buseyudulmaz", "UPmedya19!!!!" },
new string[] {"aliberkyumurtaci", "UPmedya19!!!!" },
new string[] {"yusufozanyurteri", "UPmedya19!!!!" },
new string[] {"yigityurtsever", "UPmedya19!!!!" },
new string[] {"ahmetberkyucekayali", "UPmedya19!!!!" },
new string[] {"tanberkyukselen", "UPmedya19!!!!" },
new string[] {"zarifebegumyuruk", "UPmedya19!!!!" },
new string[] {"ayseaylinyurukgil", "UPmedya19!!!!" },
new string[] {"emremiracyuzbasioglugur", "UPmedya19!!!!" },
new string[] {"ipeknazlizabun", "UPmedya19!!!!" },
new string[] {"mutesirzagli", "UPmedya19!!!!" },
new string[] {"nurferzaptiye", "UPmedya19!!!!" },
new string[] {"busragulinzeybek", "UPmedya19!!!!" },
new string[] {"bernanurzeybekci", "UPmedya19!!!!" },
new string[] {"nurdilayzilan", "UPmedya19!!!!" },
new string[] {"tunahanziyade", "UPmedya19!!!!" },
new string[] {"pakerkirisci", "UPmedya19!!!!" },
new string[] {"beyzadogan", "UPmedya19!!!!" },
new string[] {"aysegulbarutcu", "UPmedya19!!!!" },
new string[] {"sefayilmaz", "UPmedya19!!!!" },
new string[] {"elifbas", "UPmedya19!!!!" },
new string[] {"nalanaksu", "UPmedya19!!!!" },
new string[] {"nuranyuksel", "UPmedya19!!!!" },
new string[] {"erolbastug", "UPmedya19!!!!" },
new string[] {"ebubekirbakar", "UPmedya19!!!!" },
new string[] {"salihyasin", "UPmedya19!!!!" },
new string[] {"gorkemyasin", "UPmedya19!!!!" },
new string[] {"tolgasayisiz", "UPmedya19!!!!" },
new string[] {"bengisuturkmen", "UPmedya19!!!!" },
new string[] {"niyazikavuzlu", "UPmedya19!!!!" },
new string[] {"safabaykus", "UPmedya19!!!!" },
new string[] {"demirderici", "UPmedya19!!!!" },
new string[] {"burcinkasabali", "UPmedya19!!!!" },
new string[] {"dervishaktan", "UPmedya19!!!!" },
new string[] {"remzisahip", "UPmedya19!!!!" },
new string[] {"vehbisirkeci", "UPmedya19!!!!" },
new string[] {"bayrambaykal", "UPmedya19!!!!" },
new string[] {"aylasesiz", "UPmedya19!!!!" },
new string[] {"kasimguneri", "UPmedya19!!!!" },
new string[] {"mustafakindar", "UPmedya19!!!!" },
new string[] {"dilaykirgiz", "UPmedya19!!!!" },
new string[] {"onaysafir", "UPmedya19!!!!" },
new string[] {"hüsnükeskin", "UPmedya19!!!!" },
new string[] {"zulalcolak1", "UPmedya19!!!!" },
new string[] {"iremkandil1", "UPmedya19!!!!" },
new string[] {"ahmetsavci1", "UPmedya19!!!!" },
new string[] {"salihkanal1", "UPmedya19!!!!" },
new string[] {"zulalcolak11", "UPmedya19!!!!" },
new string[] {"iremkandil11", "UPmedya19!!!!" },
new string[] {"ahmetsavci11", "UPmedya19!!!!" },
new string[] {"salihkanal11", "UPmedya19!!!!" },
new string[] {"alperen", "UPmedya19!!!!" },
new string[] {"elifyilmaz", "UPmedya19!!!!" },
new string[] {"baranarslan", "UPmedya19!!!!" },
new string[] {"denizdemir", "UPmedya19!!!!" },
new string[] {"cemilkaya", "UPmedya19!!!!" },
new string[] {"aysecetin", "UPmedya19!!!!" },
new string[] {"canansahin", "UPmedya19!!!!" },
new string[] {"keremaksoy", "UPmedya19!!!!" },
new string[] {"zeynepgur", "UPmedya19!!!!" },
new string[] {"buraktekin", "UPmedya19!!!!" },
new string[] {"selinozdemir", "UPmedya19!!!!" },
new string[] {"emreyalcin", "UPmedya19!!!!" },
new string[] {"duygudemirtas", "UPmedya19!!!!" },
new string[] {"kaantuncer", "UPmedya19!!!!" },
new string[] {"melisguler", "UPmedya19!!!!" },
new string[] {"umutyildiz", "UPmedya19!!!!" },
new string[] {"damlakilic", "UPmedya19!!!!" },
new string[] {"serkanaktas", "UPmedya19!!!!" },
new string[] {"aslihankaya", "UPmedya19!!!!" },
new string[] {"mertavci", "UPmedya19!!!!" },
new string[] {"gizemuyar", "UPmedya19!!!!" },
new string[] {"burcukoc", "UPmedya19!!!!" },
new string[] {"oguzhanaydin", "UPmedya19!!!!" },
new string[] {"elifakgun", "UPmedya19!!!!" },
new string[] {"emirhanyildirim", "UPmedya19!!!!" },
new string[] {"tugbaaslan", "UPmedya19!!!!" },
new string[] {"onurdogan", "UPmedya19!!!!" },
new string[] {"busraay", "UPmedya19!!!!" },
new string[] {"furkanarikan", "UPmedya19!!!!" },
new string[] {"gamzekurt", "UPmedya19!!!!" },
new string[] {"gorkemozturk", "UPmedya19!!!!" },
new string[] {"irembulut", "UPmedya19!!!!" },
new string[] {"ugurakbulut", "UPmedya19!!!!" },
new string[] {"esraozkan", "UPmedya19!!!!" },
new string[] {"tolgagul", "UPmedya19!!!!" },
new string[] {"yaseminsen", "UPmedya19!!!!" },
new string[] {"kaanyilmaz", "UPmedya19!!!!" },
new string[] {"ilaydaaydin", "UPmedya19!!!!" },
new string[] {"serhattaskin", "UPmedya19!!!!" },
new string[] {"zehrayilmaz", "UPmedya19!!!!" },
new string[] {"ahmetcan", "UPmedya19!!!!" },
new string[] {"sudetekin", "UPmedya19!!!!" },
new string[] {"cihangunes", "UPmedya19!!!!" },
new string[] {"eceerdogan", "UPmedya19!!!!" },
new string[] {"burhanettingur", "UPmedya19!!!!" },
new string[] {"ipekkaya", "UPmedya19!!!!" },
new string[] {"emirsahin", "UPmedya19!!!!" },
new string[] {"selineren", "UPmedya19!!!!" },
new string[] {"batuhanyuksel", "UPmedya19!!!!" },
new string[] {"aslikocaman", "UPmedya19!!!!" },
new string[] {"korayucar", "UPmedya19!!!!" },
new string[] {"busraaktas", "UPmedya19!!!!" },
new string[] {"alperenyildiz", "UPmedya19!!!!" },
new string[] {"cansudemir", "UPmedya19!!!!" },
new string[] {"alpercengiz", "UPmedya19!!!!" },
new string[] {"esrayucel", "UPmedya19!!!!" },
new string[] {"berkaydemirtas", "UPmedya19!!!!" },
new string[] {"ecemdurmaz", "UPmedya19!!!!" },
new string[] {"emrekarahan", "UPmedya19!!!!" },
new string[] {"bengucelik", "UPmedya19!!!!" },
new string[] {"ermanozdemir", "UPmedya19!!!!" },
new string[] {"gizemdemirci", "UPmedya19!!!!" },
new string[] {"ufukkorkmaz", "UPmedya19!!!!" },
new string[] {"elifnazgundogan", "UPmedya19!!!!" },
new string[] {"yigityilmaz", "UPmedya19!!!!" },
new string[] {"pinarsahin", "UPmedya19!!!!" },
new string[] {"muratozkan", "UPmedya19!!!!" },
new string[] {"iremtoprak", "UPmedya19!!!!" },
new string[] {"efeerdogan", "UPmedya19!!!!" },
new string[] {"zeynepuysal", "UPmedya19!!!!" },
new string[] {"ahmetkilic", "UPmedya19!!!!" },
new string[] {"pelinyilmaz", "UPmedya19!!!!" },
new string[] {"serkanduran", "UPmedya19!!!!" },
new string[] {"berilozturk", "UPmedya19!!!!" },
new string[] {"burakyildiz", "UPmedya19!!!!" },
new string[] {"aylingunes", "UPmedya19!!!!" },
new string[] {"alptuncer", "UPmedya19!!!!" },
new string[] {"dilarakaya", "UPmedya19!!!!" },
new string[] {"taylanyilmaz", "UPmedya19!!!!" },
new string[] {"ebrukilic", "UPmedya19!!!!" },
new string[] {"emresahin", "UPmedya19!!!!" },
new string[] {"rabiayilmaz", "UPmedya19!!!!" },
new string[] {"umutdemir", "UPmedya19!!!!" },
new string[] {"eceaydin", "UPmedya19!!!!" },
new string[] {"yigitkaya", "UPmedya19!!!!" },
new string[] {"aslihantekin", "UPmedya19!!!!" },
new string[] {"furkanyilmaz", "UPmedya19!!!!" },
new string[] {"zehrayalcin", "UPmedya19!!!!" },
new string[] {"kaanyildirim", "UPmedya19!!!!" },
new string[] {"gamzekorkmaz", "UPmedya19!!!!" },
new string[] {"alpersahin", "UPmedya19!!!!" },
new string[] {"besteyilmaz", "UPmedya19!!!!" },
new string[] {"canay", "UPmedya19!!!!" },
new string[] {"damlakaya", "UPmedya19!!!!" },
new string[] {"huseyinaktas", "UPmedya19!!!!" },
new string[] {"iremerdogan", "UPmedya19!!!!" },
new string[] {"alpcan", "UPmedya19!!!!" },
new string[] {"melikeyildirim", "UPmedya19!!!!" },
new string[] {"korhanucar", "UPmedya19!!!!" },
new string[] {"zeynepyalin", "UPmedya19!!!!" }
        };

        ChromeDriver drv;
        string url = "https://www.instagram.com/accounts/emailsignup/";
        string otherurl = "https://mail.kurumsaleposta.com/mail-cx129/";


        private void button1_Click(object sender, EventArgs e)
        {

            ChromeOptions options = new ChromeOptions();

            // Tarayıcı penceresini tam ekran yapmak için ekle
            options.AddArgument("--start-maximized");
            drv = new ChromeDriver(options);
            drv.Navigate().GoToUrl(otherurl);
            System.Threading.Thread.Sleep(30000);
            var nat = drv.FindElement(By.Id("login_login")) ;
            nat.SendKeys("abdulhalimguguk@altinyapim.com");
            var ro = drv.FindElement(By.Id("login_password"));
            ro.SendKeys("UPmedya19!!!!");
            var bass = drv.FindElement(By.CssSelector(".buttons"));
            bass.Click();
            System.Threading.Thread.Sleep(12000);


            // Yeni bir sekme aç ve diğer URL'ye git
            ((IJavaScriptExecutor)drv).ExecuteScript("window.open();");
            drv.SwitchTo().Window(drv.WindowHandles[1]);
            drv.Navigate().GoToUrl(url);
            System.Threading.Thread.Sleep(6000);
            var insagr = drv.FindElement(By.Name("emailOrPhone"));
            insagr.Click();
            System.Threading.Thread.Sleep(3000);
            string accounts = " ";

            for (int i = 0; i <= 100; i++)
            {
                var firstattempt = drv.FindElement(By.CssSelector(".segoe"));
                var secondattempt = firstattempt.FindElement(By.CssSelector("._ab1y"));
                secondattempt.Click();
                var mail = secondattempt.FindElement(By.Name("emailOrPhone"));
                mail.SendKeys("abdulhalimguguk@altinyapim.com");
                var persona = secondattempt.FindElement(By.Name("fullName"));
                persona.SendKeys("abdulhalimguguk");
                System.Threading.Thread.Sleep(2000);

                var username = secondattempt.FindElements(By.CssSelector(".x1nhvcw1"));
                var klik = username[2];
                klik.Click();
                var pass = secondattempt.FindElement(By.Name("password"));
                pass.SendKeys("UPmedya19!!!!");
                var submit = secondattempt.FindElement(By.CssSelector(".x1nhvcw1"));
                submit.Click();
                System.Threading.Thread.Sleep(4000);
                var actname = secondattempt.FindElement(By.Name("username"));
                string inputValue = actname.GetAttribute("value");

                accounts = accounts + "  " + " //BOŞLUK// " + "  " + inputValue;
                var stepone = secondattempt.FindElement(By.Name("username"));
                stepone.SendKeys("abdulhalimguguk41412");
                System.Threading.Thread.Sleep(4000);

                var choose = drv.FindElement(By.CssSelector("button[class*='_acan']"));

                choose.Click();

        

                var dokun = drv.FindElements(By.CssSelector("._aj1-"));
                var cek = dokun[1];
                cek.Click();

                System.Threading.Thread.Sleep(45000);

                drv.SwitchTo().Window(drv.WindowHandles[0]);
                drv.Navigate().Refresh();
                System.Threading.Thread.Sleep(15000);
                var mailclik = drv.FindElement(By.CssSelector(".py-4"));
                mailclik.Click();
                System.Threading.Thread.Sleep(2000);


                var secondTdElement = drv.FindElement(By.CssSelector(".leading-7"));

                string kesilen = secondTdElement.Text;
                string secondTdContent = kesilen.Substring(0, 6);
                var kapat = drv.FindElements(By.CssSelector(".h-6.w-6"));
                var kapali = kapat[7];

                kapali.Click();

                drv.Navigate().Refresh();
                System.Threading.Thread.Sleep(2000);
                drv.Navigate().GoToUrl(otherurl);
                System.Threading.Thread.Sleep(2000);
                drv.SwitchTo().Window(drv.WindowHandles[1]);
                System.Threading.Thread.Sleep(2000);

                var verif = drv.FindElement(By.Name("email_confirmation_code"));
                verif.SendKeys(secondTdContent);
                System.Threading.Thread.Sleep(2000);

                var last = drv.FindElement(By.CssSelector(".x3nfvp2"));
                last.Click();
                System.Threading.Thread.Sleep(4000);
                var logout = drv.FindElements(By.CssSelector(".x18hxmgj"));
                var bas = logout[31];
            }

            richTextBox1.Text = accounts;

        }

        private void insta_Load(object sender, EventArgs e)
        {

        }
    }
}
