using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace Bot
{
    public partial class natro : Form
    {
        public natro()
        {
            InitializeComponent();
        }


        ChromeDriver drv;
        string url = "https://www.natro.com/customer/login";



        private List<string[]> mails = new List<string[]>
        {

//new string[] {"beydazog", "sifre" },
//new string[] {"aysegulbarutcuoglu", "sifre" },
//new string[] {"sefakadirbasar", "sifre" },
//new string[] {"elifetgabasegmez", "sifre" },
//new string[] {"nevinbastepe", "sifre" },
//new string[] {"mahperibastopcu", "sifre" },
//new string[] {"erolozgurbastug", "sifre" },
//new string[] {"atakbatar", "sifre" },
//new string[] {"safabatga", "sifre" },
//new string[] {"gokmenbattal", "sifre" },
//new string[] {"fazilerembatuk", "sifre" },
//new string[] {"bensubatur", "sifre" },
//new string[] {"nazimorhunbaturalp", "sifre" },
//new string[] {"safaahmetbaydar", "sifre" },
//new string[] {"demircanbaydil", "sifre" },
//new string[] {"burcinkubrabaykal", "sifre" },
//new string[] {"dervishalukbaykan", "sifre" },
//new string[] {"taylanremzibaykus", "sifre" },
//new string[] {"abdulvahapbayrakoglu", "sifre" },
//new string[] {"aygunbayram", "sifre" },
//new string[] {"aylabaytin", "sifre" },
//new string[] {"kubilaybarisbegic", "sifre" },
//new string[] {"mustafasamedbegenilmis", "sifre" },
//new string[] {"berfindilaybekaroglu", "sifre" },
//new string[] {"ibrahimonatbengi", "sifre" },
//new string[] {"jutenyabenan", "sifre" },
//new string[] {"hulkibent", "sifre" },
//new string[] {"mustafadogukanberberoglu", "sifre" },
//new string[] {"hunerberk", "sifre" },
//new string[] {"busegizemberker", "sifre" },
//new string[] {"halimebeydag", "sifre" },
//new string[] {"didembicaksiz", "sifre" },
//new string[] {"mihrinazbilal", "sifre" },
//new string[] {"lalbilgec", "sifre" },
//new string[] {"senaybilgen", "sifre" },
//new string[] {"remzibilgi", "sifre" },
//new string[] {"armaganbilgic", "sifre" },
//new string[] {"celikbilgir", "sifre" },
//new string[] {"kubratansubilgit", "sifre" },
//new string[] {"ulucemrebinbay", "sifre" },
//new string[] {"mehmetbugrahanbirgili", "sifre" },
//new string[] {"doguscanbiriz", "sifre" },
//new string[] {"altanboy", "sifre" },
//new string[] {"bengisuboya", "sifre" },
//new string[] {"onurtaylanboylu", "sifre" },
//new string[] {"ayserenboyuktas", "sifre" },
//new string[] {"pekinboz", "sifre" },
//new string[] {"aksubozdag", "sifre" },
//new string[] {"arkanbozdemir", "sifre" },
//new string[] {"iltemboztepe", "sifre" },
//new string[] {"betulbozyer", "sifre" },
//new string[] {"ogunbolge", "sifre" },
//new string[] {"ibrahimhakkibugey", "sifre" },
//new string[] {"onaybugdaypinari", "sifre" },
//new string[] {"cankizbulgan", "sifre" },
//new string[] {"arzucanbulgur", "sifre" },
//new string[] {"asiyeburabak", "sifre" },
//new string[] {"ahmetyasinburak", "sifre" },
//new string[] {"yaprakbural", "sifre" },
//new string[] {"aledabuyuran", "sifre" },
//new string[] {"canguneybulbul", "sifre" },
//new string[] {"mahmutbilalbulend", "sifre" },
//new string[] {"salihazeynepbulent", "sifre" },
//new string[] {"melikedilarabuyukfirat", "sifre" },
//new string[] {"hayriyebuyukgungor", "sifre" },
//new string[] {"sebihabuyukozturk", "sifre" },
//new string[] {"mehmetcanakcaozoglu", "sifre" },
//new string[] {"mehmetenescanan", "sifre" },
//new string[] {"kurtbeycanbagi", "sifre" },
//new string[] {"mustafatahacanbek", "sifre" },
//new string[] {"senanurcandan", "sifre" },
//new string[] {"abdullahemirhancaner", "sifre" },
//new string[] {"mustafakeremcansu", "sifre" },
//new string[] {"doktoracanuyar", "sifre" },
//new string[] {"seyitceran", "sifre" },
//new string[] {"selmasimgeceylan", "sifre" },
//new string[] {"askimchiklyaukova", "sifre" },
//new string[] {"ozgurchoi", "sifre" },
//new string[] {"tugcecibooglu", "sifre" },
//new string[] {"ozerseckinciddi", "sifre" },
//new string[] {"balkincigerlioglu", "sifre" },
//new string[] {"yucelcivan", "sifre" },
//new string[] {"sansalcosan", "sifre" },
//new string[] {"oguzcancosandal", "sifre" },
//new string[] {"mayiscumali", "sifre" },
//new string[] {"busracuce", "sifre" },
//new string[] {"afraselcencagan", "sifre" },
//new string[] {"gonulcagatay", "sifre" },
//new string[] {"doganguncaglar", "sifre" },
//new string[] {"elifegecaglayan", "sifre" },
//new string[] {"ozencakan", "sifre" },
//new string[] {"dilhancakanel", "sifre" },
//new string[] {"maralcakici", "sifre" },
//new string[] {"mahirecalim", "sifre" },
//new string[] {"hacibayramufukcamas", "sifre" },
//new string[] {"oltuncanga", "sifre" },
//new string[] {"onelcapa", "sifre" },
//new string[] {"bayulkencaprak", "sifre" },
//new string[] {"dilserencarici", "sifre" },
//new string[] {"elifbeyzacark", "sifre" },
//new string[] {"elvancatal", "sifre" },
//new string[] {"esimcaylar", "sifre" },
//new string[] {"senacekmecelioglu", "sifre" },
//new string[] {"muhammeduzeyircekmeci", "sifre" },
//new string[] {"aydinmertcelebican", "sifre" },
//new string[] {"cagkancelenlioglu", "sifre" },
//new string[] {"zumracelik", "sifre" },
//new string[] {"bayarcelik", "sifre" },
//new string[] {"gonulgulcelikagi", "sifre" },
//new string[] {"ecepinarceliker", "sifre" },
//new string[] {"mehmettarikcelikkol", "sifre" },
//new string[] {"elifecerci", "sifre" },
//new string[] {"efecancetintas", "sifre" },
//new string[] {"ridvancikikci", "sifre" },
//new string[] {"haticegamzecinar", "sifre" },
//new string[] {"yansihilalcinaroglu", "sifre" },
//new string[] {"omaccingir", "sifre" },
//new string[] {"erhanciray", "sifre" },
//new string[] {"suhedacicekli", "sifre" },
//new string[] {"unkancini", "sifre" },
//new string[] {"ahmetgazicintan", "sifre" },
//new string[] {"seheriremcitfci", "sifre" },
//new string[] {"gurbuzcivici", "sifre" },
//new string[] {"zulalcolak", "sifre" },
//new string[] {"ozanegecomu", "sifre" },
//new string[] {"hilalebruconay", "sifre" },
//new string[] {"aybencorumlu", "sifre" },
//new string[] {"abdulbakicotur", "sifre" },
//new string[] {"nevacuhadar", "sifre" },
//new string[] {"oznurculhaoglu", "sifre" },
//new string[] {"olgundadalioglu", "sifre" },
//new string[] {"cagriatahandagar", "sifre" },
//new string[] {"ozalpdagbag", "sifre" },
//new string[] {"husneaysundal", "sifre" },
//new string[] {"aydonatdalkilic", "sifre" },
//new string[] {"ezgindalli", "sifre" },
//new string[] {"refiyesedadalyaprak", "sifre" },
//new string[] {"esaterdemdanis", "sifre" },
//new string[] {"ayseneslihandasdemir", "sifre" },
//new string[] {"fetullahdavutoglu", "sifre" },
//new string[] {"mertgorkemdayioglu", "sifre" },
//new string[] {"ergundegirmendereli", "sifre" },
//new string[] {"hulyadelichasan", "sifre" },
//new string[] {"dogaelifdelice", "sifre" },
//new string[] {"muhammedbazitdeliloglu", "sifre" },
//new string[] {"miracdemiroren", "sifre" },
//new string[] {"hureldemiriz", "sifre" },
//new string[] {"somerdemiroglu", "sifre" },
//new string[] {"ayselaysudemirsatan", "sifre" },
//new string[] {"mehmetkemaldengizek", "sifre" },
//new string[] {"alyadenizgunu", "sifre" },
//new string[] {"zeynepbusraderdemez", "sifre" },
//new string[] {"tubanurdereli", "sifre" },
//new string[] {"dalayderya", "sifre" },
//new string[] {"bedirdestereci", "sifre" },
//new string[] {"rumeysairemdevecel", "sifre" },
//new string[] {"osmansinandevrim", "sifre" },
//new string[] {"salihacanandivarci", "sifre" },
//new string[] {"sametemredikbas", "sifre" },
//new string[] {"haldundincturk", "sifre" },
//new string[] {"goncaguldiri", "sifre" },
//new string[] {"ziyadogramaci", "sifre" },
//new string[] {"zehrapelindoger", "sifre" },
//new string[] {"selimsharefdokulmez", "sifre" },
//new string[] {"firuzedonder", "sifre" },
//new string[] {"dorukdenizdoner", "sifre" },
//new string[] {"cisilzeynepdonmez", "sifre" },
//new string[] {"tugcedudu", "sifre" },
//new string[] {"enverdur", "sifre" },
//new string[] {"sanberdurak", "sifre" },
//new string[] {"birsendurmus", "sifre" },
//new string[] {"tacmindurmusoglu", "sifre" },
//new string[] {"karanalpdursun", "sifre" },
//new string[] {"oktemduymus", "sifre" },
//new string[] {"elanazdulgerbaki", "sifre" },
//new string[] {"fidandundar", "sifre" },
//new string[] {"barindusenkalkar", "sifre" },
//new string[] {"mehmetermanduzbayir", "sifre" },
//new string[] {"cemefeedes", "sifre" },
//new string[] {"eremedibalimp", "sifre" },
//new string[] {"volkaneyupefsin", "sifre" },
//new string[] {"ibrahimalptekinege", "sifre" },
//new string[] {"gungorerkinegeli", "sifre" },
//new string[] {"caginegin", "sifre" },
//new string[] {"alphanekercan", "sifre" },
//new string[] {"laleekrem", "sifre" },
//new string[] {"bagiscanelbasi", "sifre" },
//new string[] {"mertcemelicin", "sifre" },
//new string[] {"ahmetsenceremikoglu", "sifre" },
//new string[] {"akifeerbay", "sifre" },
//new string[] {"burcerbil", "sifre" },
//new string[] {"nadireerbul", "sifre" },
//new string[] {"huseyinzeydercoskun", "sifre" },
//new string[] {"aynurgulercument", "sifre" },
//new string[] {"samederek", "sifre" },
//new string[] {"cemozanerim", "sifre" },
//new string[] {"baharcemreerin", "sifre" },
//new string[] {"rekinerkek", "sifre" },
//new string[] {"huseyinserkanerkekli", "sifre" },
//new string[] {"ibrahimcandaserki", "sifre" },
//new string[] {"benizerkmen", "sifre" },
//new string[] {"hasanburakerkoc", "sifre" },
//new string[] {"selmanerkosan", "sifre" },
//new string[] {"hanifenurerkovan", "sifre" },
//new string[] {"alpereminerkus", "sifre" },
//new string[] {"elifkevsereroglu", "sifre" },
//new string[] {"abdullahmerterol", "sifre" },
//new string[] {"ciselersin", "sifre" },
//new string[] {"ilkinersoz", "sifre" },
//new string[] {"cantekinerten", "sifre" },
//new string[] {"onurkeremertepinar", "sifre" },
//new string[] {"ismaileneseruzun", "sifre" },
//new string[] {"hamideryildiz", "sifre" },
//new string[] {"tuncaeryilmaz", "sifre" },
//new string[] {"arslanerzurumlu", "sifre" },
//new string[] {"neslihanbusraesat", "sifre" },
//new string[] {"lutfiyesenaesen", "sifre" },
//new string[] {"belinesendemir", "sifre" },
//new string[] {"rukiyeesgin", "sifre" },
//new string[] {"islameshaqzada", "sifre" },
//new string[] {"batirayeski", "sifre" },
//new string[] {"suheylesvap", "sifre" },
//new string[] {"yargiyektaese", "sifre" },
//new string[] {"elzemevrenos", "sifre" },
//new string[] {"ilgazeyipisiren", "sifre" },
//new string[] {"ongareyyupoglu", "sifre" },
//new string[] {"faikezber", "sifre" },
//new string[] {"turanfahri", "sifre" },
//new string[] {"okbayfatih", "sifre" },
//new string[] {"latifefatin", "sifre" },
//new string[] {"eyuporhunfindik", "sifre" },
//new string[] {"irfananilfindikci", "sifre" },
//new string[] {"ertugfuruncuoglu", "sifre" },
//new string[] {"berhudangarip", "sifre" },
//new string[] {"nihangazitepe", "sifre" },
//new string[] {"meneksegeben", "sifre" },
//new string[] {"senizgebologlu", "sifre" },
//new string[] {"zeynepsenahangecioglu", "sifre" },
//new string[] {"hayrianilgeckin", "sifre" },
//new string[] {"muazzezecegemalmaz", "sifre" },
//new string[] {"keremcahitgencoglu", "sifre" },
//new string[] {"sadikcangezmis", "sifre" },
//new string[] {"resmiyeelifgirgin", "sifre" },
//new string[] {"nergizgilim", "sifre" },
//new string[] {"mehmetgokalpginovic", "sifre" },
//new string[] {"mehmetaligirgin", "sifre" },
//new string[] {"abdullahhalitgolba", "sifre" },
//new string[] {"tilbegoc", "sifre" },
//new string[] {"kubragocmen", "sifre" },
//new string[] {"kubilaygodek", "sifre" },
//new string[] {"busemgokceaslan", "sifre" },
//new string[] {"banuhangokcek", "sifre" },
//new string[] {"orgungokhan", "sifre" },
//new string[] {"melikegoksoy", "sifre" },
//new string[] {"yesimgolmes", "sifre" },
//new string[] {"nilufergonay", "sifre" },
//new string[] {"denizhangonul", "sifre" },
//new string[] {"suedagoreke", "sifre" },
//new string[] {"ersingorgulu", "sifre" },
//new string[] {"sahabettingorguner", "sifre" },
//new string[] {"ayseelifgorur", "sifre" },
//new string[] {"nazimberkegoven", "sifre" },
//new string[] {"meltemgoymen", "sifre" },
//new string[] {"abdulhalimguguk", "sifre" },
//new string[] {"gultenguducu", "sifre" },
//new string[] {"isinbikegulcan", "sifre" },
//new string[] {"vediagulcin", "sifre" },
//new string[] {"fatmasenaguldogus", "sifre" },
//new string[] {"omerokangulebakan", "sifre" },
//new string[] {"aybikegulec", "sifre" },
//new string[] {"bektasgulenc", "sifre" },
//new string[] {"emircanguleryuz", "sifre" },
//new string[] {"mertergulkan", "sifre" },
//new string[] {"sevgitutkugulluce", "sifre" },
//new string[] {"denktasgulsen", "sifre" },
//new string[] {"koksalgultas", "sifre" },
//new string[] {"hasanfahrigultepe", "sifre" },
//new string[] {"oymengumussoy", "sifre" },
//new string[] {"eylemgunduz", "sifre" },
//new string[] {"melekdilergunel", "sifre" },
//new string[] {"argunguneri", "sifre" },
//new string[] {"mehmetyektaguneyi", "sifre" },
//new string[] {"yaseminervaguntek", "sifre" },
//new string[] {"gunangural", "sifre" },
//new string[] {"osmancihangurdemir", "sifre" },
//new string[] {"okyanusgurel", "sifre" },
//new string[] {"mertalicangures", "sifre" },
//new string[] {"zeynepdogagurses", "sifre" },
//new string[] {"tarikguven", "sifre" },
//new string[] {"birgenguvener", "sifre" },
//new string[] {"ahmetkorhanguzel", "sifre" },
//new string[] {"manolyaguzeller", "sifre" },
//new string[] {"mustafaberkayguzeloglu", "sifre" },
//new string[] {"mehmetanilhacialioglu", "sifre" },
//new string[] {"ahmetfurkanhacilar", "sifre" },
//new string[] {"fazilethacioglu", "sifre" },
//new string[] {"kivilcimhadi", "sifre" },
//new string[] {"cisilhazalhafiz", "sifre" },
//new string[] {"ferayhakverdi", "sifre" },
//new string[] {"busranurhalacoglu", "sifre" },
//new string[] {"selinsilahalicilar", "sifre" },
//new string[] {"yeterhamamcioglu", "sifre" },
//new string[] {"ramazantarikhamarat", "sifre" },
//new string[] {"boranhamidi", "sifre" },
//new string[] {"tazikahilalhamzaoglu", "sifre" },
//new string[] {"aynurdilanhanci", "sifre" },
//new string[] {"aymanhangul", "sifre" },
//new string[] {"berrakharman", "sifre" },
//new string[] {"erkdehaharmankaya", "sifre" },
//new string[] {"perihanhaykir", "sifre" },
//new string[] {"turhanonurhirlak", "sifre" },
//new string[] {"furkanhizarcioglu", "sifre" },
//new string[] {"mustafaalihicyilmam", "sifre" },
//new string[] {"muhammedsefahilal", "sifre" },
//new string[] {"argunhilmi", "sifre" },
//new string[] {"fadikhimoglu", "sifre" },
//new string[] {"ahmethakkihirik", "sifre" },
//new string[] {"mustafasefahopaci", "sifre" },
//new string[] {"toykanhorata", "sifre" },
//new string[] {"selimehuner", "sifre" },
//new string[] {"denizcanilik", "sifre" },
//new string[] {"aysezeynebiricioglu", "sifre" },
//new string[] {"mustafafurkanisinay", "sifre" },
//new string[] {"sudeibrahim", "sifre" },
//new string[] {"gucluicten", "sifre" },
//new string[] {"katyailgezdi", "sifre" },
//new string[] {"halidilhan", "sifre" },
//new string[] {"nihalilisu", "sifre" },
//new string[] {"elifnisanimamoglu", "sifre" },
//new string[] {"emineselcenimre", "sifre" },
//new string[] {"tevfikinal", "sifre" },
//new string[] {"ibrahimkaganincekara", "sifre" },
//new string[] {"sidarinceoglu", "sifre" },
//new string[] {"nesliipcizade", "sifre" },
//new string[] {"ihsanvehbiipekoglu", "sifre" },
//new string[] {"necatiirsoy", "sifre" },
//new string[] {"zerinishakoglu", "sifre" },
//new string[] {"dursunkorelisgoren", "sifre" },
//new string[] {"ahusenisguzar", "sifre" },
//new string[] {"uzelkabatas", "sifre" },
//new string[] {"melisezgikabayuka", "sifre" },
//new string[] {"saziyekabukcu", "sifre" },
//new string[] {"berguzarkacaranoglu", "sifre" },
//new string[] {"omerfarukkadi", "sifre" },
//new string[] {"daghankadoglu", "sifre" },
//new string[] {"unzilekalfaoglu", "sifre" },
//new string[] {"sezerkalsin", "sifre" },
//new string[] {"sensoykalyoncu", "sifre" },
//new string[] {"necatikamisli", "sifre" },
//new string[] {"sahankandasoglu", "sifre" },
//new string[] {"necipfazilkanli", "sifre" },
//new string[] {"muharremkanmaz", "sifre" },
//new string[] {"zeynepfigenkantarci", "sifre" },
//new string[] {"cilaykapsiz", "sifre" },
//new string[] {"sunakaraaslanli", "sifre" },
//new string[] {"ahmetcankarabacak", "sifre" },
//new string[] {"asyasemakarabag", "sifre" },
//new string[] {"gulsenakarabiyik", "sifre" },
//new string[] {"fatmabusrakarabiyikli", "sifre" },
//new string[] {"arcakarabulut", "sifre" },
//new string[] {"abdullatifkaracabey", "sifre" },
//new string[] {"tugrakaracan", "sifre" },
//new string[] {"emirdogankaracay", "sifre" },
//new string[] {"halukbariskaracesme", "sifre" },
//new string[] {"seyitahmetkaradag", "sifre" },
//new string[] {"cevzakaradalan", "sifre" },
//new string[] {"mustafaemirkarademir", "sifre" },
//new string[] {"ilgarpamirkaraismail", "sifre" },
//new string[] {"serenkarakan", "sifre" },
//new string[] {"busrahazalkarakaplan", "sifre" },
//new string[] {"nacikarakaya", "sifre" },
//new string[] {"oguzselimkarakelle", "sifre" },
//new string[] {"faikaltugkarakoca", "sifre" },
//new string[] {"dincolkaralar", "sifre" },
//new string[] {"ceyhunkadirkaramollaoglu", "sifre" },
//new string[] {"tayyibekaranisoglu", "sifre" },
//new string[] {"hayriyegulkararti", "sifre" },
//new string[] {"gulsanemkarasapan", "sifre" },
//new string[] {"yeldakardas", "sifre" },
//new string[] {"kuntayyigitkarga", "sifre" },
//new string[] {"ahmetberkekargin", "sifre" },
//new string[] {"kivanckasaci", "sifre" },
//new string[] {"virakasemllar", "sifre" },
//new string[] {"orselkaska", "sifre" },
//new string[] {"esmaecekavak", "sifre" },
//new string[] {"benekkavas", "sifre" },
//new string[] {"halenurkavasoglu", "sifre" },
//new string[] {"umitkavukcu", "sifre" },
//new string[] {"ishakkayacan", "sifre" },
//new string[] {"ibrahimkayahan", "sifre" },
//new string[] {"odulkayali", "sifre" },
//new string[] {"egesarpkayar", "sifre" },
//new string[] {"mahmutonurkayhan", "sifre" },
//new string[] {"mimozakaynamis", "sifre" },
//new string[] {"cemilekazici", "sifre" },
//new string[] {"belitkece", "sifre" },
//new string[] {"aslinurkefal", "sifre" },
//new string[] {"acunkeles", "sifre" },
//new string[] {"behcetkutaykerem", "sifre" },
//new string[] {"aysemervekerigan", "sifre" },
//new string[] {"behinkerimov", "sifre" },
//new string[] {"fatmahilalkesbic", "sifre" },
//new string[] {"nunkesgin", "sifre" },
//new string[] {"ahmetmehdikeskin", "sifre" },
//new string[] {"mehpareketeci", "sifre" },
//new string[] {"muhammedikbalkevkir", "sifre" },
//new string[] {"alaatinkilcadir", "sifre" },
//new string[] {"hamitkildir", "sifre" },
//new string[] {"muktedirkilincarslan", "sifre" },
//new string[] {"onurabdikina", "sifre" },
//new string[] {"lokmankirbiyik", "sifre" },
//new string[] {"mertkirgiz", "sifre" },
//new string[] {"gulenaykiris", "sifre" },
//new string[] {"mursidekirkpinar", "sifre" },
//new string[] {"furkanfatihkirmizi", "sifre" },
//new string[] {"haticebusrakirtas", "sifre" },
//new string[] {"yasarfatiheneskirtay", "sifre" },
//new string[] {"parlakiryayla", "sifre" },
//new string[] {"gulcekivilcim", "sifre" },
//new string[] {"yasinburakkizil", "sifre" },
//new string[] {"alimkizilboga", "sifre" },
//new string[] {"iscankizilca", "sifre" },
//new string[] {"evrenburakkizilirmak", "sifre" },
//new string[] {"ozgegizemkizilkaya", "sifre" },
//new string[] {"dilsadnurkiziltug", "sifre" },
//new string[] {"eneskizmaz", "sifre" },
//new string[] {"yalcinkilmen", "sifre" },
//new string[] {"aliaydinkirezcik", "sifre" },
//new string[] {"skaancankisial", "sifre" },
//new string[] {"maisamkisin", "sifre" },
//new string[] {"mehmethankocabas", "sifre" },
//new string[] {"irazhakkinakocabiyik", "sifre" },
//new string[] {"yigithankocademir", "sifre" },
//new string[] {"iremcerenkocak", "sifre" },
//new string[] {"yusufsuhakocbaba", "sifre" },
//new string[] {"iptalkocsoy", "sifre" },
//new string[] {"abdulsametkonakoglu", "sifre" },
//new string[] {"mehmetbariskondakcioglu", "sifre" },
//new string[] {"ahenkkontaci", "sifre" },
//new string[] {"hayatkonyar", "sifre" },
//new string[] {"yigitalperenkoparan", "sifre" },
//new string[] {"gunerkorkmazcan", "sifre" },
//new string[] {"berfuiremkoskulu", "sifre" },
//new string[] {"ilkekotan", "sifre" },
//new string[] {"aliozankovanci", "sifre" },
//new string[] {"fatmanurkoytak", "sifre" },
//new string[] {"ibrahimfehmikoyunsev", "sifre" },
//new string[] {"aslinazkozakcioglu", "sifre" },
//new string[] {"ataalpkocer", "sifre" },
//new string[] {"macidekokcu", "sifre" },
//new string[] {"mustafakoken", "sifre" },
//new string[] {"aybarkormukcu", "sifre" },
//new string[] {"sahinkose", "sifre" },
//new string[] {"tunckoybasi", "sifre" },
//new string[] {"ruveydakuday", "sifre" },
//new string[] {"gurolkudu", "sifre" },
//new string[] {"chakankukaraci", "sifre" },
//new string[] {"eliskul", "sifre" },
//new string[] {"selmakuloglu", "sifre" },
//new string[] {"huseyinkumru", "sifre" },
//new string[] {"acaroguztankundakci", "sifre" },
//new string[] {"guneykunter", "sifre" },
//new string[] {"ozgesilakuntman", "sifre" },
//new string[] {"sevalkurtan", "sifre" },
//new string[] {"bernakurtulus", "sifre" },
//new string[] {"seriferkamkutanoglu", "sifre" },
//new string[] {"meliketamarakutlay", "sifre" },
//new string[] {"aycagkucukbey", "sifre" },
//new string[] {"sadiyekucukkase", "sifre" },
//new string[] {"alikucukler", "sifre" },
//new string[] {"nigarkulahlioglu", "sifre" },
//new string[] {"gulbenkurk", "sifre" },
//new string[] {"ayseferhundekurkcu", "sifre" },
//new string[] {"eralpkurum", "sifre" },
//new string[] {"alperenkusku", "sifre" },
//new string[] {"zehrasenamadran", "sifre" },
//new string[] {"gunduzmagden", "sifre" },
//new string[] {"osmanemremaldar", "sifre" },
//new string[] {"kubatmalekiravasan", "sifre" },
//new string[] {"baharelcinmammadov", "sifre" },
//new string[] {"nuelifmardanlou", "sifre" },
//new string[] {"mehmeterenmasaraci", "sifre" },
//new string[] {"melismasir", "sifre" },
//new string[] {"fatimamatur", "sifre" },
//new string[] {"karacamaydagil", "sifre" },
//new string[] {"zaferenginmemisler", "sifre" },
//new string[] {"duygunmenguc", "sifre" },
//new string[] {"havagulmercimekci", "sifre" },
//new string[] {"ariffurkanmerdan", "sifre" },
//new string[] {"halitcanmert", "sifre" },
//new string[] {"pertevmetin", "sifre" },
//new string[] {"selismezarci", "sifre" },
//new string[] {"galipmirzanli", "sifre" },
//new string[] {"tulaytugcemisoglu", "sifre" },
//new string[] {"ahusemohamed", "sifre" },
//new string[] {"barbarosmollaametali", "sifre" },
//new string[] {"lawrencetezohmorbenli", "sifre" },
//new string[] {"gorkemmorelli", "sifre" },
//new string[] {"abdurahmanmorgul", "sifre" },
//new string[] {"zulcenahmortepe", "sifre" },
//new string[] {"saadetnurmumcu", "sifre" },
//new string[] {"hasangurkanmuratoglu", "sifre" },
//new string[] {"sehmusmursal", "sifre" },
//new string[] {"berkanmusaoglu", "sifre" },
//new string[] {"erselmuslu", "sifre" },
//new string[] {"batugmutman", "sifre" },
//new string[] {"dilsumunif", "sifre" },
//new string[] {"erdogannalbant", "sifre" },
//new string[] {"batinalbantoglu", "sifre" },
//new string[] {"turkannalcaci", "sifre" },
//new string[] {"gulpinarnamdar", "sifre" },
//new string[] {"gokcinnamli", "sifre" },
//new string[] {"ulkernayman", "sifre" },
//new string[] {"eslemnerkis", "sifre" },
//new string[] {"nazliozumnisanci", "sifre" },
//new string[] {"alkiznumanoglu", "sifre" },
//new string[] {"nimetocalan", "sifre" },
//new string[] {"ismailegecanocar", "sifre" },
//new string[] {"kameroduncu", "sifre" },
//new string[] {"gencaloguz", "sifre" },
//new string[] {"kursatoguzfp", "sifre" },
//new string[] {"irembasakoguzhan", "sifre" },
//new string[] {"ulascanokan", "sifre" },
//new string[] {"tunahanokatan", "sifre" },
//new string[] {"izelokcu", "sifre" },
//new string[] {"elizokkaya", "sifre" },
//new string[] {"cisilokumus", "sifre" },
//new string[] {"keremcanonus", "sifre" },
//new string[] {"keremcanoraloglu", "sifre" },
//new string[] {"taliporhan", "sifre" },
//new string[] {"besteorhon", "sifre" },
//new string[] {"ismetorman", "sifre" },
//new string[] {"mustafaboraozgun", "sifre" },
//new string[] {"oganocal", "sifre" },
//new string[] {"ahmetcihatogredik", "sifre" },
//new string[] {"vahideokmen", "sifre" },
//new string[] {"murtazaolmezler", "sifre" },
//new string[] {"gonenonder", "sifre" },
//new string[] {"zeyneptubaonen", "sifre" },
//new string[] {"gunkutonoglu", "sifre" },
//new string[] {"farukdogukanoreroglu", "sifre" },
//new string[] {"gunyolufukorge", "sifre" },
//new string[] {"selimcanors", "sifre" },
//new string[] {"raifaniloter", "sifre" },
//new string[] {"okandenizovul", "sifre" },
//new string[] {"mustafaselmanoyus", "sifre" },
//new string[] {"ayseloz", "sifre" },
//new string[] {"ajlanozakyol", "sifre" },
//new string[] {"ayhanfurkanozar", "sifre" },
//new string[] {"ebrueceozata", "sifre" },
//new string[] {"berfinelifozay", "sifre" },
//new string[] {"muhammetozaydin", "sifre" },
//new string[] {"ardaalanozayral", "sifre" },
//new string[] {"isilayozbey", "sifre" },
//new string[] {"selaleozbir", "sifre" },
//new string[] {"oktayemirozcan", "sifre" },
//new string[] {"gunizozdel", "sifre" },
//new string[] {"murathanozdil", "sifre" },
//new string[] {"kadirrozdincer", "sifre" },
//new string[] {"anilseckinozelci", "sifre" },
//new string[] {"dilaynurozer", "sifre" },
//new string[] {"semsiyigitozev", "sifre" },
//new string[] {"ilayozgenc", "sifre" },
//new string[] {"bediaozgenoglu", "sifre" },
//new string[] {"kadiranilozgezgin", "sifre" },
//new string[] {"ecemozgul", "sifre" },
//new string[] {"girayozgumus", "sifre" },
//new string[] {"abdulsamedozgur", "sifre" },
//new string[] {"tenduozgurun", "sifre" },
//new string[] {"eminetugceozirk", "sifre" },
//new string[] {"mehmetyusaozkol", "sifre" },
//new string[] {"egehanozkok", "sifre" },
//new string[] {"mustafaerenozkul", "sifre" },
//new string[] {"iremnurozmez", "sifre" },
//new string[] {"fahirozpak", "sifre" },
//new string[] {"aliahmetozpercin", "sifre" },
//new string[] {"eyupcanozperk", "sifre" },
//new string[] {"mervenurozpolat", "sifre" },
//new string[] {"muhammerozsoydan", "sifre" },
//new string[] {"arkadasnecatioztas", "sifre" },
//new string[] {"gunaydinozteker", "sifre" },
//new string[] {"zuleyhaoztemel", "sifre" },
//new string[] {"mustafaoguzhanoztunc", "sifre" },
//new string[] {"okcanozturk", "sifre" },
//new string[] {"muhammedeminozuberk", "sifre" },
//new string[] {"gamzenurpadak", "sifre" },
//new string[] {"muhammedkerempak", "sifre" },
//new string[] {"zeynepecehanpakdemirli", "sifre" },
//new string[] {"safakpakdil", "sifre" },
//new string[] {"sukranpakkan", "sifre" },
//new string[] {"altaypaksoy", "sifre" },
//new string[] {"hicretpalanko", "sifre" },
//new string[] {"nusretpalut", "sifre" },
//new string[] {"omerpamukcu", "sifre" },
//new string[] {"mehmetziyapancar", "sifre" },
//new string[] {"aysuparlak", "sifre" },
//new string[] {"cenappasolar", "sifre" },
//new string[] {"atapazar", "sifre" },
//new string[] {"sabanpehlevan", "sifre" },
//new string[] {"humapehlivan", "sifre" },
//new string[] {"ekinesmepehlivanli", "sifre" },
//new string[] {"mehtappehlivanoglu", "sifre" },
//new string[] {"mehmetsaidpekdogdu", "sifre" },
//new string[] {"cihadpektemek", "sifre" },
//new string[] {"senaypiristina", "sifre" },
//new string[] {"umranpocan", "sifre" },
//new string[] {"evrenpomay", "sifre" },
//new string[] {"kevserportakal", "sifre" },
//new string[] {"ziynetposbiyik", "sifre" },
//new string[] {"muhammedkutayposlu", "sifre" },
//new string[] {"efganpuca", "sifre" },
//new string[] {"baharmervepurcu", "sifre" },
//new string[] {"dilaraaysimramis", "sifre" },
//new string[] {"tomurcukrauf", "sifre" },
//new string[] {"simaviremzi", "sifre" },
//new string[] {"esmaedarevan", "sifre" },
//new string[] {"utkurona", "sifre" },
//new string[] {"nurselirusan", "sifre" },
//new string[] {"urcuksaatciler", "sifre" },
//new string[] {"cagataysabah", "sifre" },
//new string[] {"niyaziumutsabri", "sifre" },
//new string[] {"caglasacak", "sifre" },
//new string[] {"ayseberresadak", "sifre" },
//new string[] {"aligurelsadiklar", "sifre" },
//new string[] {"tayyipsadikoglu", "sifre" },
//new string[] {"nesatsadri", "sifre" },
//new string[] {"ferudunsaf", "sifre" },
//new string[] {"aysesalihasakarya", "sifre" },
//new string[] {"emrecansakaryali", "sifre" },
//new string[] {"omersefasaltuk", "sifre" },
//new string[] {"ahmetenessamanci", "sifre" },
//new string[] {"aliizzeddinsamar", "sifre" },
//new string[] {"fatmaserrasami", "sifre" },
//new string[] {"arcansaparca", "sifre" },
//new string[] {"gunnazsar", "sifre" },
//new string[] {"simgenursaracgil", "sifre" },
//new string[] {"nesringokcesaraclar", "sifre" },
//new string[] {"ayseisilsaray", "sifre" },
//new string[] {"nuecesarialtun", "sifre" },
//new string[] {"muhteremsarioglu", "sifre" },
//new string[] {"esengulsariteke", "sifre" },
//new string[] {"cansunursavca", "sifre" },
//new string[] {"necmettinsaydam", "sifre" },
//new string[] {"melikenursultansaydan", "sifre" },
//new string[] {"ayciceksaygin", "sifre" },
//new string[] {"muhammetfatihsayici", "sifre" },
//new string[] {"orkidesayil", "sifre" },
//new string[] {"ozgeelifsayrac", "sifre" },
//new string[] {"refiasazak", "sifre" },
//new string[] {"yaseminbaharschmitz", "sifre" },
//new string[] {"minasel", "sifre" },
//new string[] {"servetecenazselcuk", "sifre" },
//new string[] {"sevdenurselvi", "sifre" },
//new string[] {"abdullahfurkansenturk", "sifre" },
//new string[] {"olcasevcan", "sifre" },
//new string[] {"nebisever", "sifre" },
//new string[] {"yaseminsevigen", "sifre" },
//new string[] {"gunayseydaoglu", "sifre" },
//new string[] {"zuleyhaseyfi", "sifre" },
//new string[] {"tunayseyhan", "sifre" },
//new string[] {"tanjuseymen", "sifre" },
//new string[] {"muhammedsaitseytin", "sifre" },
//new string[] {"mehmetakifsirac", "sifre" },
//new string[] {"kaankubilaysimavli", "sifre" },
//new string[] {"aysegulsobaci", "sifre" },
//new string[] {"canelsofyalioglu", "sifre" },
//new string[] {"rabiakubrasolak", "sifre" },
//new string[] {"ikbalsongur", "sifre" },
//new string[] {"esatsoyadi", "sifre" },
//new string[] {"yunusgokersoylu", "sifre" },
//new string[] {"kanaatsoyulmaz", "sifre" },
//new string[] {"cengizhansokel", "sifre" },
//new string[] {"gencaysoker", "sifre" },
//new string[] {"gazanfersoylemez", "sifre" },
//new string[] {"dorukhansozeri", "sifre" },
//new string[] {"hesnaezgisozuer", "sifre" },
//new string[] {"ilknursozumcetin", "sifre" },
//new string[] {"firuzsu", "sifre" },
//new string[] {"hasangokaysugoturen", "sifre" },
//new string[] {"guzaysular", "sifre" },
//new string[] {"ozgunmertsuna", "sifre" },
//new string[] {"iparsuyunu", "sifre" },
//new string[] {"guralsuhan", "sifre" },
//new string[] {"nazberilsuleymanzade", "sifre" },
//new string[] {"irissureyya", "sifre" },
//new string[] {"gulselinsurmeli", "sifre" },
//new string[] {"alpersadi", "sifre" },
//new string[] {"abbassahabettinoglu", "sifre" },
//new string[] {"nugayesahin", "sifre" },
//new string[] {"buraktansahingoz", "sifre" },
//new string[] {"efemustafasakarcan", "sifre" },
//new string[] {"behiyesamlioglu", "sifre" },
//new string[] {"yagmurhelinsarkisla", "sifre" },
//new string[] {"aslicansekercioglu", "sifre" },
//new string[] {"cigdemsekeryan", "sifre" },
//new string[] {"taykutsenozen", "sifre" },
//new string[] {"fehimesuhedasenbas", "sifre" },
//new string[] {"oguncsencan", "sifre" },
//new string[] {"gurkansendag", "sifre" },
//new string[] {"sezanursendiller", "sifre" },
//new string[] {"sehersengul", "sifre" },
//new string[] {"nejatsenocak", "sifre" },
//new string[] {"yelizsenyurd", "sifre" },
//new string[] {"alitarikserbetci", "sifre" },
//new string[] {"adaseref", "sifre" },
//new string[] {"yunusemreserifoglu", "sifre" },
//new string[] {"melikedenizsevkin", "sifre" },
//new string[] {"mehvestabak", "sifre" },
//new string[] {"furkanalicantabanli", "sifre" },
//new string[] {"aykantabir", "sifre" },
//new string[] {"ahmetutkutac", "sifre" },
//new string[] {"dilaratacgin", "sifre" },
//new string[] {"miracayberktahir", "sifre" },
//new string[] {"kardelentahmazoglu", "sifre" },
//new string[] {"pinargultalantemur", "sifre" },
//new string[] {"areltalas", "sifre" },
//new string[] {"aysegulbegumtanbasi", "sifre" },
//new string[] {"farshadtanis", "sifre" },
//new string[] {"guzinduygutanrikulu", "sifre" },
//new string[] {"ebruummuhantarakci", "sifre" },
//new string[] {"numantarhan", "sifre" },
//new string[] {"celikertarlakazan", "sifre" },
//new string[] {"seventas", "sifre" },
//new string[] {"balatasak", "sifre" },
//new string[] {"kokertascioglu", "sifre" },
//new string[] {"batughantasgin", "sifre" },
//new string[] {"guventasli", "sifre" },
//new string[] {"ecegultasyurek", "sifre" },
//new string[] {"beyzanurtatli", "sifre" },
//new string[] {"keremardatatlisu", "sifre" },
//new string[] {"abdussamettayan", "sifre" },
//new string[] {"tilbesunaytayfun", "sifre" },
//new string[] {"ismailtazegul", "sifre" },
//new string[] {"ogurtecer", "sifre" },
//new string[] {"aktanteker", "sifre" },
//new string[] {"ahmetbugratekin", "sifre" },
//new string[] {"denizhaleteksan", "sifre" },
//new string[] {"umutsalihtektas", "sifre" },
//new string[] {"isiltantekten", "sifre" },
//new string[] {"erdemtemizer", "sifre" },
//new string[] {"atalayfurkantenim", "sifre" },
//new string[] {"alialptercan", "sifre" },
//new string[] {"sabihaesraterzi", "sifre" },
//new string[] {"yakupcantetik", "sifre" },
//new string[] {"talyatezmen", "sifre" },
//new string[] {"tugbanurtiftikci", "sifre" },
//new string[] {"aktactogay", "sifre" },
//new string[] {"ahucantogan", "sifre" },
//new string[] {"saimesuratokac", "sifre" },
//new string[] {"dogcantokali", "sifre" },
//new string[] {"bilhantokatlioglu", "sifre" },
//new string[] {"muhammedbilaltokdogan", "sifre" },
//new string[] {"sukruozumcantoker", "sifre" },
//new string[] {"ecenurtokgoz", "sifre" },
//new string[] {"baysaltolunay", "sifre" },
//new string[] {"mugetopal", "sifre" },
//new string[] {"dilsahtopalan", "sifre" },
//new string[] {"salihatopoyan", "sifre" },
//new string[] {"tarcantoptan", "sifre" },
//new string[] {"ruyasutorgutalp", "sifre" },
//new string[] {"gulsendilantorol", "sifre" },
//new string[] {"velittoygar", "sifre" },
//new string[] {"perkertufan", "sifre" },
//new string[] {"lerzantugrul", "sifre" },
//new string[] {"nuetugmen", "sifre" },
//new string[] {"yasaremretuncay", "sifre" },
//new string[] {"aybukeaycaturna", "sifre" },
//new string[] {"muhammetmustafaturul", "sifre" },
//new string[] {"lalezarturunc", "sifre" },
//new string[] {"iyilemtudes", "sifre" },
//new string[] {"istemifurkantufekci", "sifre" },
//new string[] {"ilseltufekcioglu", "sifre" },
//new string[] {"muhammedcanturkmenoglu", "sifre" },
//new string[] {"mebruketurkoglu", "sifre" },
//new string[] {"ummugulsumtut", "sifre" },
//new string[] {"gokborimertubay", "sifre" },
//new string[] {"zeynepneslihanucanok", "sifre" },
//new string[] {"malikucar", "sifre" },
//new string[] {"umutmertucma", "sifre" },
//new string[] {"enginsuugur", "sifre" },
//new string[] {"mervegululas", "sifre" },
//new string[] {"ugurulug", "sifre" },
//new string[] {"canerhazaruluhan", "sifre" },
//new string[] {"aysimulupinar", "sifre" },
//new string[] {"arifegulbizulusoy", "sifre" },
//new string[] {"haticebernaulutas", "sifre" },
//new string[] {"kuntayurganci", "sifre" },
//new string[] {"berraurgancioglu", "sifre" },
//new string[] {"zehranazusanmaz", "sifre" },
//new string[] {"ahuelausluer", "sifre" },
//new string[] {"bedriyeserayusta", "sifre" },
//new string[] {"alpdoraustabasi", "sifre" },
//new string[] {"gulumseusumi", "sifre" },
//new string[] {"enginugurusak", "sifre" },
//new string[] {"gizemnuruyu", "sifre" },
//new string[] {"kemaltolgauz", "sifre" },
//new string[] {"tahsinuzun", "sifre" },
//new string[] {"ugurcanuzundonekoglu", "sifre" },
//new string[] {"arsunuzunirmak", "sifre" },
//new string[] {"ozgecanucler", "sifre" },
//new string[] {"siddikauctas", "sifre" },
//new string[] {"imranmusaviulgey", "sifre" },
//new string[] {"ebrarunay", "sifre" },
//new string[] {"acilayunlu", "sifre" },
//new string[] {"muzehherzeynepunlu", "sifre" },
//new string[] {"aybirgenurkmezturk", "sifre" },
//new string[] {"akifuskent", "sifre" },
//new string[] {"volkanustbas", "sifre" },
//new string[] {"ozmenustunel", "sifre" },
//new string[] {"gulenderusenmez", "sifre" },
//new string[] {"muzafferuzar", "sifre" },
//new string[] {"medihaburcuvanli", "sifre" },
//new string[] {"sulhadinvarli", "sifre" },
//new string[] {"buketyildiz", "sifre" },
//new string[] {"serifyakupoglu", "sifre" },
//new string[] {"senasimayyalcinkaya", "sifre" },
//new string[] {"mumunenihanyalcintas", "sifre" },
//new string[] {"edisyalmac", "sifre" },
//new string[] {"alagulyalman", "sifre" },
//new string[] {"nazimbircanyalova", "sifre" },
//new string[] {"ekinegeyamanoglu", "sifre" },
//new string[] {"aysemelisayanik", "sifre" },
//new string[] {"anilgorkemyapar", "sifre" },
//new string[] {"cavityaprak", "sifre" },
//new string[] {"gulsahyarbas", "sifre" },
//new string[] {"isiltiyardimci", "sifre" },
//new string[] {"aysecansuyasa", "sifre" },
//new string[] {"muhammedaliduranyasin", "sifre" },
//new string[] {"nurullahyasin", "sifre" },
//new string[] {"nuvityavaser", "sifre" },
//new string[] {"taneryay", "sifre" },
//new string[] {"sezenyayla", "sifre" },
//new string[] {"tunahansalihyazicigil", "sifre" },
//new string[] {"raifyazicioglu", "sifre" },
//new string[] {"dilarazeynepyeksan", "sifre" },
//new string[] {"muhammedenesyel", "sifre" },
//new string[] {"busrahilalyelegen", "sifre" },
//new string[] {"meryemsumeyyeyeniceli", "sifre" },
//new string[] {"sayanyeniev", "sifre" },
//new string[] {"aykutyerlikaya", "sifre" },
//new string[] {"ilkyazyerliyurt", "sifre" },
//new string[] {"gulsenyerzhan", "sifre" },
//new string[] {"nurettinhazaryesilcimen", "sifre" },
//new string[] {"alifurkanyesilova", "sifre" },
//new string[] {"kolcakyikilmazsoy", "sifre" },
//new string[] {"selenelifyildirimer", "sifre" },
//new string[] {"azelyayildizdoken", "sifre" },
//new string[] {"ibrahimenginyildizoglu", "sifre" },
//new string[] {"sadriyirmibescik", "sifre" },
//new string[] {"enessaidyolcu", "sifre" },
//new string[] {"eseryorgun", "sifre" },
//new string[] {"selcenyorulmaz", "sifre" },
//new string[] {"alaaddinyondem", "sifre" },
//new string[] {"jiyanyoruten", "sifre" },
//new string[] {"buseyudulmaz", "sifre" },
//new string[] {"aliberkyumurtaci", "sifre" },
//new string[] {"yusufozanyurteri", "sifre" },
//new string[] {"yigityurtsever", "sifre" },
//new string[] {"ahmetberkyucekayali", "sifre" },
//new string[] {"tanberkyukselen", "sifre" },
//new string[] {"zarifebegumyuruk", "sifre" },
//new string[] {"ayseaylinyurukgil", "sifre" },
//new string[] {"emremiracyuzbasioglugur", "sifre" },
//new string[] {"ipeknazlizabun", "sifre" },
//new string[] {"mutesirzagli", "sifre" },
//new string[] {"nurferzaptiye", "sifre" },
//new string[] {"busragulinzeybek", "sifre" },
//new string[] {"bernanurzeybekci", "sifre" },
//new string[] {"nurdilayzilan", "sifre" },
//new string[] {"tunahanziyade", "sifre" },
//new string[] {"pakerkirisci", "sifre" },
//new string[] {"beyzadogan", "sifre" },
//new string[] {"aysegulbarutcu", "sifre" },
//new string[] {"sefayilmaz", "sifre" },
//new string[] {"elifbas", "sifre" },
//new string[] {"nalanaksu", "sifre" },
//new string[] {"nuranyuksel", "sifre" },
//new string[] {"erolbastug", "sifre" },
//new string[] {"ebubekirbakar", "sifre" },
//new string[] {"salihyasin", "sifre" },
//new string[] {"gorkemyasin", "sifre" },
//new string[] {"tolgasayisiz", "sifre" },
//new string[] {"bengisuturkmen", "sifre" },
//new string[] {"niyazikavuzlu", "sifre" },
//new string[] {"safabaykus", "sifre" },
//new string[] {"demirderici", "sifre" },
//new string[] {"burcinkasabali", "sifre" },
//new string[] {"dervishaktan", "sifre" },
//new string[] {"remzisahip", "sifre" },
//new string[] {"vehbisirkeci", "sifre" },
//new string[] {"bayrambaykal", "sifre" },
//new string[] {"aylasesiz", "sifre" },
//new string[] {"kasimguneri", "sifre" },
//new string[] {"mustafakindar", "sifre" },
//new string[] {"dilaykirgiz", "sifre" },
//new string[] {"onaysafir", "sifre" },
//new string[] {"hüsnükeskin", "sifre" },
//new string[] {"zulalcolak1", "sifre" },
//new string[] {"iremkandil1", "sifre" },
//new string[] {"ahmetsavci1", "sifre" },
//new string[] {"salihkanal1", "sifre" },
//new string[] {"zulalcolak11", "sifre" },
//new string[] {"iremkandil11", "sifre" },
//new string[] {"ahmetsavci11", "sifre" },
//new string[] {"salihkanal11", "sifre" },
//new string[] {"alperen", "sifre" },
//new string[] {"elifyilmaz", "sifre" },
//new string[] {"baranarslan", "sifre" },
//new string[] {"denizdemir", "sifre" },
//new string[] {"cemilkaya", "sifre" },
//new string[] {"aysecetin", "sifre" },
//new string[] {"canansahin", "sifre" },
//new string[] {"keremaksoy", "sifre" },
//new string[] {"zeynepgur", "sifre" },
//new string[] {"buraktekin", "sifre" },
//new string[] {"selinozdemir", "sifre" },
//new string[] {"emreyalcin", "sifre" },
//new string[] {"duygudemirtas", "sifre" },
//new string[] {"kaantuncer", "sifre" },
//new string[] {"melisguler", "sifre" },
//new string[] {"umutyildiz", "sifre" },
//new string[] {"damlakilic", "sifre" },
//new string[] {"serkanaktas", "sifre" },
//new string[] {"aslihankaya", "sifre" },
//new string[] {"mertavci", "sifre" },
//new string[] {"gizemuyar", "sifre" },
//new string[] {"burcukoc", "sifre" },
//new string[] {"oguzhanaydin", "sifre" },
//new string[] {"elifakgun", "sifre" },
//new string[] {"emirhanyildirim", "sifre" },
//new string[] {"tugbaaslan", "sifre" },
//new string[] {"onurdogan", "sifre" },
//new string[] {"busraay", "sifre" },
//new string[] {"furkanarikan", "sifre" },
//new string[] {"gamzekurt", "sifre" },
//new string[] {"gorkemozturk", "sifre" },
//new string[] {"irembulut", "sifre" },
//new string[] {"ugurakbulut", "sifre" },
//new string[] {"esraozkan", "sifre" },
//new string[] {"tolgagul", "sifre" },
//new string[] {"yaseminsen", "sifre" },
//new string[] {"kaanyilmaz", "sifre" },
//new string[] {"ilaydaaydin", "sifre" },
//new string[] {"serhattaskin", "sifre" },
//new string[] {"zehrayilmaz", "sifre" },
//new string[] {"ahmetcan", "sifre" },
//new string[] {"sudetekin", "sifre" },
//new string[] {"cihangunes", "sifre" },
//new string[] {"eceerdogan", "sifre" },
//new string[] {"burhanettingur", "sifre" },
//new string[] {"ipekkaya", "sifre" },
//new string[] {"emirsahin", "sifre" },
//new string[] {"selineren", "sifre" },
//new string[] {"batuhanyuksel", "sifre" },
//new string[] {"aslikocaman", "sifre" },
//new string[] {"korayucar", "sifre" },
//new string[] {"busraaktas", "sifre" },
//new string[] {"alperenyildiz", "sifre" },
//new string[] {"cansudemir", "sifre" },
//new string[] {"alpercengiz", "sifre" },
//new string[] {"esrayucel", "sifre" },
//new string[] {"berkaydemirtas", "sifre" },
//new string[] {"ecemdurmaz", "sifre" },
//new string[] {"emrekarahan", "sifre" },
//new string[] {"bengucelik", "sifre" },
//new string[] {"ermanozdemir", "sifre" },
//new string[] {"gizemdemirci", "sifre" },
//new string[] {"ufukkorkmaz", "sifre" },
//new string[] {"elifnazgundogan", "sifre" },
//new string[] {"yigityilmaz", "sifre" },
//new string[] {"pinarsahin", "sifre" },
//new string[] {"muratozkan", "sifre" },
//new string[] {"iremtoprak", "sifre" },
//new string[] {"efeerdogan", "sifre" },
//new string[] {"zeynepuysal", "sifre" },
//new string[] {"ahmetkilic", "sifre" },
//new string[] {"pelinyilmaz", "sifre" },
//new string[] {"serkanduran", "sifre" },
//new string[] {"berilozturk", "sifre" },
//new string[] {"burakyildiz", "sifre" },
//new string[] {"aylingunes", "sifre" },
//new string[] {"alptuncer", "sifre" },
//new string[] {"dilarakaya", "sifre" },
//new string[] {"taylanyilmaz", "sifre" },
//new string[] {"ebrukilic", "sifre" },
//new string[] {"emresahin", "sifre" },
//new string[] {"rabiayilmaz", "sifre" },
//new string[] {"umutdemir", "sifre" },
//new string[] {"eceaydin", "sifre" },
//new string[] {"yigitkaya", "sifre" },
//new string[] {"aslihantekin", "sifre" },
//new string[] {"furkanyilmaz", "sifre" },
//new string[] {"zehrayalcin", "sifre" },
//new string[] {"kaanyildirim", "sifre" },
//new string[] {"gamzekorkmaz", "sifre" },
//new string[] {"alpersahin", "sifre" },
//new string[] {"besteyilmaz", "sifre" },
//new string[] {"canay", "sifre" },
//new string[] {"damlakaya", "sifre" },
//new string[] {"huseyinaktas", "sifre" },
//new string[] {"iremerdogan", "sifre" },
//new string[] {"alpcan", "sifre" },
//new string[] {"melikeyildirim", "sifre" },
//new string[] {"korhanucar", "sifre" },
//new string[] {"zeynepyalin", "sifre" }

        };




        private void RunNatro(string username, string password)
        {
            ChromeOptions options = new ChromeOptions();

            // Tarayıcı penceresini tam ekran yapmak için ekle
            options.AddArgument("--start-maximized");
            drv = new ChromeDriver(options);
            drv.Navigate().GoToUrl(url);

            // Sayfanın yüklenmesini bekleyin
            System.Threading.Thread.Sleep(5000); // Dikkat: Daha iyi bir yaklaşım için explicit wait kullanılabilir.

            // Kullanıcı adı ve şifre alanlarını bul ve doldur
            var usernameField = drv.FindElement(By.Id("Customer_Number"));
            var passwordField = drv.FindElement(By.Id("Customer_Password"));

            usernameField.SendKeys(username);
            passwordField.SendKeys(password);

            // Giriş yap butonunu bul ve tıkla
            var loginButton = drv.FindElement(By.CssSelector(".btn-justified"));
            loginButton.Click();

            // Giriş işleminin tamamlanmasını bekleyin
            System.Threading.Thread.Sleep(5000); // Yine, daha iyi bir yöntem explicit wait olacaktır.
            string adres = "https://www.natro.com/musteri/HOSTINGAktifler1.asp";
            drv.Navigate().GoToUrl(adres);
            System.Threading.Thread.Sleep(5000);

            var passElements = drv.FindElements(By.CssSelector(".btn-sm"));
            if (passElements.Count > 0)
            {
                // Element bulundu, üzerinde işlem yapabilirsiniz.
                var pass = passElements[1]; // Listeden ilk elementi alın.
                pass.Click();
                System.Threading.Thread.Sleep(5000); // Gerekli işlemler için bekleme.
            }
            else
            {
                // Element bulunamadı, hata yönetimi veya alternatif bir işlem yapabilirsiniz.
                Console.WriteLine("Aranan element bulunamadı.");
            }





            System.Threading.Thread.Sleep(65000);
            string links = "https://cloudpanel.natro.com/Mail/AccountPost?hostName=hostadiniz&clearSession=true&isInline=true&jobType=0";
            drv.Navigate().GoToUrl(links);
            System.Threading.Thread.Sleep(65000);

            for (int i = 0; i <= mails.Count; i++)
            {
                string kadi = mails[i][0].ToString();
                string sifre = mails[i][1].ToString();




                var act = drv.FindElement(By.Id("FullName"));
                act.SendKeys(kadi);



                var accountname = drv.FindElement(By.Id("AccountName"));
                accountname.SendKeys(kadi);
                System.Threading.Thread.Sleep(1000);


                var passsword = drv.FindElement(By.Id("Password"));
                passsword.SendKeys(sifre);
                System.Threading.Thread.Sleep(1000);


                var RePassword = drv.FindElement(By.Id("RePassword"));
                RePassword.SendKeys(sifre);
                System.Threading.Thread.Sleep(1000);



                var chekle = drv.FindElement(By.Id("WebMailEnabled"));
                chekle.Click();

                var sub = drv.FindElement(By.Id("accPostBtn"));
                sub.Click();
                System.Threading.Thread.Sleep(30000);

                act.Clear();
                accountname.Clear();
                passsword.Clear();
                RePassword.Clear();
                sub.Click();
                int completedLoops = i + 1;
                label1.Text = $"Loops Completed: {completedLoops} out of {mails.Count}";
                Application.DoEvents();
            }


            drv.Quit();








        }



        private void button1_Click(object sender, EventArgs e)
        {
            RunNatro("kullaniciadi", "sifre");
        }
    }
}
